// Contract playbook text for x-contract-review-014.

const issue = (id, topic, why, standard, fallback1, fallback2, redline, approver, lookFor, modelClause) => [
  `### ${id} ${topic}`,
  {
    table: [
      [`Item`, `Position`],
      [`Why it matters`, why],
      [`Standard position`, standard],
      [`Fallback 1`, fallback1],
      [`Fallback 2`, fallback2],
      [`Red line`, redline],
      [`Approver`, approver],
      [`Look for`, lookFor],
      [`Model clause`, modelClause],
    ],
  },
];

export const PLAYBOOK = [
  `# PT Contoso Niaga Nusantara Tbk and subsidiaries: Contract Playbook, Cloud, SaaS and Managed IT Services`,
  `Version 3.1. Effective 1 July 2026. Owner: Legal & Compliance, Siti Rahmawati, Head of Legal & Compliance. Approved by Hendra Wijaya, General Counsel & Corporate Secretary.`,
  `This playbook is the internal contracting standard for PT Contoso Niaga Nusantara Tbk (CN01) and its subsidiaries, including Contoso Niaga Malaysia Sdn. Bhd. It is written for Legal, Procurement, Enterprise IT, Information Security, Privacy, Finance and business owners who negotiate cloud, SaaS and managed IT services. The commercial objective is to buy technology quickly without leaving the Group exposed to silent online terms, unmanaged data transfers, weak exit rights, or liability positions that would be unacceptable after an outage or regulatory inquiry.`,
  `## 1. Purpose and scope`,
  `This playbook applies to contracts for public cloud, private cloud, platform services, SaaS subscriptions, managed operations, managed security, hosted databases, observability services, professional services that are bundled with those offerings, and similar technology arrangements where aggregate fees exceed USD 50,000 per year or local-currency equivalent. It applies whether the contracting entity is CN01, a direct Indonesian subsidiary, Contoso Niaga Malaysia Sdn. Bhd., or another subsidiary signing an order form under a group master agreement.`,
  `It does not replace specific legal advice to CN01 or any subsidiary on an unusual transaction. It is not legal advice to suppliers, customers, consultants or other third parties. If a business owner sends this playbook outside the Group, it loses its value as an internal negotiation tool and may disclose negotiation limits. Do not send it to a vendor.`,
  `Use it in every review of a cloud, SaaS or managed services agreement. Read the signed master agreement, schedules, order forms, statements of work, data processing addendum, online service terms, support policy, acceptable use policy, subprocessor list and any document incorporated by URL. Review every issue P01 to P19 even if the contract looks short or the vendor says the document is standard. Record the verdict in the Contract Review Record, quote the clause reference, and escalate in line with the matrix before signature.`,
  `For mixed regional transactions, apply the stricter position where the same service processes both Indonesian and Malaysian data. If a subsidiary signs a separate order form, record the subsidiary name, governing law, data location and price protections in the review record. For regulated financial services, lending, payments, insurance, investment or similar activities, stop and ask Legal & Compliance whether additional OJK, Bank Indonesia, Bank Negara Malaysia or other regulator obligations apply.`,
  `## 2. How to use the positions`,
  `Standard means the contract meets the Group's preferred position. The Legal Counsel assigned to the matter may clear the clause if the drafting is clear, the negotiated order form is not overridden elsewhere, and the position is reflected in all incorporated documents. A standard position still needs a clause reference in the Contract Review Record.`,
  `Fallback 1 means a pre-approved compromise. The approving role is stated in the issue. If the issue says Head of Legal, the Legal Counsel must send the clause, business reason and proposed mitigation to the Head of Legal before signature. Where the issue says Legal Counsel, the Legal Counsel may approve it directly, provided the deviation is accurately recorded.`,
  `Fallback 2 means a more significant risk acceptance. It normally requires the General Counsel and any named functional approver. Do not treat a vendor's statement that its paper is non-negotiable as approval. The business owner must explain why the deal is still needed, what alternative suppliers were considered, and what practical mitigations will be implemented.`,
  `Red line means the position is not acceptable for normal contracting. Legal Counsel must ask for a redline. If the vendor refuses, the matter is escalated as an exception only where the President Director approves on the recommendation of the General Counsel and the Board Risk Committee is notified. Some red lines are listed as Not acceptable because the risk is structural: for example, an English-only agreement with an Indonesian party, or a provider right to train models on Customer Content.`,
  `Not addressed means the contract is silent. Silence is not automatically acceptable. If the playbook says the issue must be addressed, propose the model clause or obtain the listed approval for signing without it. Each deviation must be recorded in the Contract Review Record with the clause reference, what the contract says, the verdict, proposed redline, approver and status. Anything beyond the listed fallback requires the approver in the matrix before signature.`,
  `## 3. Approval matrix`,
  {
    table: [
      [`Role`, `May approve`, `Conditions and records required`],
      [`Legal Counsel (Commercial)`, `Standard positions and pre-approved fallbacks expressly marked Legal Counsel, including P05 payment at 30 days from invoice date.`, `Record the clause reference, verdict and any agreed redline. Confirm that order forms and online terms do not reverse the position.`],
      [`Head of Legal`, `Fallback 1 items marked Head of Legal, and Not addressed items where the issue assigns Head of Legal.`, `Approval may be by email. The request must include business owner justification, risk summary and final clause wording.`],
      [`General Counsel`, `Fallback 2 items, beyond-fallback items, and issues marked General Counsel.`, `Required before signature. General Counsel may impose operational mitigations, signing conditions or board-level notice.`],
      [`General Counsel with CFO`, `Commercial risk items such as term, renewal, price increases and termination economics where the issue names CFO.`, `Finance must confirm budget impact, remaining-commitment exposure and accounting treatment before execution.`],
      [`General Counsel with CISO`, `Security, service continuity, audit, exit and operational resilience issues where CISO is named.`, `CISO must confirm technical mitigation, monitoring, incident response and exit feasibility.`],
      [`General Counsel with DPO`, `Privacy, breach notification, cross-border transfer, subprocessor and data-use issues where DPO is named.`, `DPO must confirm data categories, transfer safeguards, notification timelines and records of processing.`],
      [`President Director exception`, `Red lines only on General Counsel recommendation.`, `Not acceptable in the ordinary course. Board Risk Committee notification is required for any signed exception.`],
    ],
  },
  `## 4. The positions`,
  ...issue(
    `P01`,
    `Order of precedence and online terms`,
    `Order of precedence determines which promise survives when the vendor paper conflicts with the negotiated order form. For cloud services, the highest-risk terms are often outside the signed MSA: service terms, support policies, acceptable use policies and subprocessor lists maintained at a URL. If online terms prevail or may change unilaterally, hard-won special conditions such as Jakarta hosting and a price hold can disappear without a signature.`,
    `The signed documents govern. Order Form Special Conditions prevail over the MSA; the MSA prevails over any referenced online terms. No unilateral changes.`,
    `Online terms only as a dated, versioned copy attached at signature; later changes apply only if they do not reduce Customer protections (Head of Legal).`,
    `None`,
    `Online terms that prevail over the signed agreement, or that the provider can change unilaterally.`,
    `Not acceptable (exception: President Director on GC recommendation)`,
    `order of precedence; online terms; as updated from time to time; effective when posted; notwithstanding; special conditions; order form ranks after; URL; acceptable use policy; support policy`,
    `If there is any conflict, the following order applies: (1) the Order Form and its Special Conditions, (2) the body of this Agreement, (3) schedules and attachments, and (4) any referenced online terms. Online terms are incorporated only in the version attached at signature, and later changes do not apply unless agreed in writing by Customer.`,
  ),
  ...issue(
    `P02`,
    `Contract language (Indonesian entity)`,
    `Contracts with an Indonesian party require careful handling under Law No. 24 of 2009 and Presidential Regulation No. 63 of 2019. The West Jakarta District Court decision in Nine AM case 451/Pdt.G/2012/PN.Jkt.Bar is a practical warning that language-law arguments can be used to challenge an English-only agreement. We do not rely on a waiver of Indonesian language requirements, especially for a listed Indonesian group.`,
    `For CN01: bilingual Indonesian and English, signed at the same time; English may prevail. For CM01: English is acceptable.`,
    `Indonesian version delivered and signed within 30 days of signature, with an undertaking to cooperate (Head of Legal).`,
    `None`,
    `English-only agreement with an Indonesian party, or any waiver of Law 24/2009.`,
    `Not acceptable`,
    `English only; English prevails; no translation required; waives Law 24/2009; waives Presidential Regulation 63/2019; Bahasa Indonesia; language version`,
    `For any Indonesian Customer entity, this Agreement is executed in Indonesian and English. The parties agree that both versions are signed at the same time; if there is inconsistency, the English version prevails to the extent permitted by applicable law.`,
  ),
  ...issue(
    `P03`,
    `Term and renewal`,
    `Long automatic renewals create budget lock-in and weaken leverage when service quality is poor. A 36-month initial term may be justified for migration and price certainty, but renewal should be an active business decision. Procurement must have enough notice to run a renewal assessment and, if needed, a competitive process.`,
    `Initial term up to 36 months. Renewal only by written agreement.`,
    `Automatic renewal for 12-month periods with at least 60 days notice and a written reminder from the provider 30 days before the notice deadline (Head of Legal).`,
    `None`,
    `None`,
    `General Counsel and CFO`,
    `automatic renewal; successive renewal terms; 36 months; notice at least 90 days; unless either party gives notice; evergreen; renewal term; non-cancellable`,
    `The Initial Subscription Term is stated in the Order Form and may not exceed 36 months. Any Renewal Term requires written agreement signed by both parties before the then-current term expires; continued use alone does not renew the Services.`,
  ),
  ...issue(
    `P04`,
    `Price increases`,
    `Price mechanics are a core commercial control because migration costs make switching difficult after go-live. The Order Form price hold must not be defeated by an MSA clause or online price schedule. Resetting to list price at renewal can turn a negotiated multi-year business case into an unfunded commitment.`,
    `Fees fixed for the initial term. At renewal, increase capped at Indonesian CPI (BPS) and never more than 5%.`,
    `Annual increase up to 5% from year 2 (CFO).`,
    `Up to 7% at renewal only (General Counsel and CFO).`,
    `None`,
    `General Counsel and CFO`,
    `greater of; CPI; BPS; list price; then-current rates; anniversary; renewal; price schedule; provider may increase; fees fixed; price hold`,
    `Fees in an Order Form are fixed for the Initial Subscription Term. Any renewal increase must be agreed in the Renewal Order Form and may not exceed the lower of Indonesian CPI published by BPS and 5% unless approved under Customer's internal delegation.`,
  ),
  ...issue(
    `P05`,
    `Payment terms`,
    `Payment timing affects cash forecasting and dispute leverage, but this issue is lower risk than service continuity, data and liability. Procurement should still ensure invoices are correct and tied to the contracted entity. Thirty days from invoice date is pre-approved at Legal Counsel level for this category, even though the preferred drafting is from receipt of a correct invoice.`,
    `Payment within 30 days of receipt of a correct invoice.`,
    `30 days from invoice date (Legal Counsel).`,
    `None`,
    `None`,
    `Legal Counsel`,
    `30 days; invoice date; receipt of invoice; annually in advance; correct invoice; undisputed amount; late payment; interest`,
    `Customer will pay undisputed Fees within 30 days after receipt of a correct invoice issued to the contracting entity named in the Order Form. The parties will work promptly to resolve disputed amounts, and Customer will pay any agreed balance within 30 days after resolution.`,
  ),
  ...issue(
    `P06`,
    `Suspension of service`,
    `Suspension of a production cloud platform can stop sales, warehouse operations and partner ordering faster than a contractual termination. Providers need emergency rights for genuine threats, but commercial suspension for a late invoice should not occur without clear notice and a cure period. The clause must limit emergency action to the affected component and require immediate notice.`,
    `Suspension for non-payment only after 30 days written notice for undisputed amounts. Immediate suspension only for a genuine security emergency, limited to the affected component, with immediate notice.`,
    `15 days written notice for non-payment (Head of Legal).`,
    `None`,
    `Suspension of production systems without notice for commercial reasons.`,
    `General Counsel`,
    `suspend immediately; with or without notice; reasonably suspects; acceptable use policy; unpaid; five days; security emergency; affected component; commercial reasons`,
    `Provider may suspend Services for non-payment only for undisputed amounts that remain unpaid 30 days after written notice. Provider may take immediate, proportionate action only for a genuine security emergency, limited to the affected Service component, and must notify Customer without delay.`,
  ),
  ...issue(
    `P07`,
    `Service levels and remedies`,
    `Portal Mitra is a revenue and partner-facing platform, so availability remedies must drive behaviour rather than merely rebate a small amount. Credits capped at 10% and described as a sole remedy do not compensate for lost orders, escalation costs or reputational damage. A chronic-failure termination right is essential where repeated outages show the platform is not operationally fit.`,
    `99.9% monthly availability; credits up to 25% of the monthly fee; credits are not the sole remedy; right to terminate if availability is missed in 3 months out of any 6; claims within 60 days.`,
    `99.5% availability accepted only if credits are not the sole remedy AND the chronic-failure termination right is included (General Counsel and CISO).`,
    `None`,
    `None`,
    `General Counsel and CISO`,
    `99.5%; 99.9%; scheduled maintenance; emergency maintenance; sole and exclusive remedy; service credits; 15 days; monthly fee; terminate; three months out of six`,
    `Provider will make the production Services available at least 99.9% each calendar month, excluding agreed Scheduled Maintenance. Service Credits are without prejudice to Customer's other rights, and Customer may terminate the affected Services if availability is missed in any three months in a rolling six-month period.`,
  ),
  ...issue(
    `P08`,
    `Limitation of liability (general cap)`,
    `The general cap should be proportionate to annual spend and realistic loss scenarios. A 12-month fee cap is a recognised compromise for enterprise cloud services, but it leaves little room where implementation, migration, workarounds and business interruption overlap. Any cap below six months of fees is not commercially meaningful for a critical platform.`,
    `The greater of the Fees paid or payable in the 24 months preceding the claim, or USD 2,000,000.`,
    `Fees paid or payable in the 12 months preceding the claim (Head of Legal).`,
    `Fees paid or payable in the 12 months preceding the claim, with a minimum floor of USD 500,000 (General Counsel).`,
    `Cap below 6 months of fees.`,
    `Head of Legal`,
    `total aggregate liability; 12 months preceding; paid or payable; six months; minimum floor; USD 500,000; limitation of liability; aggregate cap`,
    `Subject to the exclusions and separate data-breach cap, each party's total aggregate liability is limited to the greater of the Fees paid or payable in the 24 months preceding the claim and USD 2,000,000.`,
  ),
  ...issue(
    `P09`,
    `Excluded losses`,
    `Excluded-loss wording often removes the very losses the Group would suffer in a technology failure. Data restoration, breach notification, remediation costs and regulatory fines caused by the provider's breach should not be treated as remote or unrecoverable. If the supplier insists on a separate data-breach cap, confirm that these losses remain claimable within that cap.`,
    `Costs of restoring data, breach notification and remediation costs, and regulatory fines caused by the provider's breach are recoverable direct losses.`,
    `Same, but subject to the data-breach cap in P10 (General Counsel).`,
    `None`,
    `None`,
    `General Counsel`,
    `excluded losses; indirect; consequential; loss or corruption of data; costs of restoring data; substitute services; fines; penalties; regulator; remediation`,
    `The exclusions of indirect and consequential loss do not exclude costs of restoring Customer Data, breach notification and remediation costs, costs of procuring reasonable temporary substitute services, or fines and penalties to the extent caused by Provider's breach of the Agreement.`,
  ),
  ...issue(
    `P10`,
    `Data breach liability`,
    `A low data-breach cap transfers the supplier's operational security risk back to the Group. The issue is especially serious where a general clause overrides a good-looking DPA cap through a notwithstanding provision. A cap below the general liability cap is inconsistent with the risk profile of personal data, partner records, order history and hosted business data.`,
    `Uncapped, or a separate super-cap of at least 3x the general cap.`,
    `Super-cap of 2x the general cap (General Counsel, CISO and DPO).`,
    `None`,
    `Any data-breach cap lower than the general cap.`,
    `Not acceptable`,
    `notwithstanding anything to the contrary; DPA cap; security incident; three months; lower than general cap; super-cap; personal data; breach of DPA`,
    `Notwithstanding the general liability cap, Provider's liability arising from a Security Incident, breach of the DPA, unauthorised disclosure of Customer Data or breach of confidentiality is uncapped or, if a cap is required, subject to a separate cap of at least three times the general liability cap.`,
  ),
  ...issue(
    `P11`,
    `Security incident notification`,
    `Notification timing must support CN01's and Contoso Niaga Malaysia's own statutory and customer communications. Under Indonesia's UU 27/2022, Article 46 requires notification of a personal data protection failure within 3 x 24 hours to the relevant parties and authority; Malaysia's PDPA 2010 as amended includes a 72-hour notification expectation to the Commissioner under section 12B. A clock that starts only after provider confirmation may leave the Group with no usable time.`,
    `Notice within 24 hours of the provider becoming aware, with the information needed for Customer's own notifications (Indonesia: 3x24 hours to data subjects and the authority under UU PDP Art. 46; Malaysia: 72 hours to the Commissioner under PDPA s.12B).`,
    `48 hours from awareness (CISO and DPO).`,
    `None`,
    `Any clock that starts at "confirmation" or runs longer than 72 hours.`,
    `General Counsel, CISO and DPO`,
    `without undue delay; seven Business Days; confirms; after confirmation; becomes aware; 24 hours; 48 hours; 72 hours; Security Incident; information needed`,
    `Provider must notify Customer within 24 hours after becoming aware of any actual or reasonably suspected Security Incident. The notice must include available facts, affected systems and data, mitigation steps, and updates reasonably required for Customer to meet its notification obligations.`,
  ),
  ...issue(
    `P12`,
    `Data location, transfers and subprocessors`,
    `Data location commitments are central to this deal because the Order Form promises Jakarta hosting for CN01. Indonesia's UU 27/2022 Article 56 requires cross-border transfer safeguards; Malaysia's PDPA 2010 section 129 regulates transfers outside Malaysia. If the counterparty business ever involves regulated financial services, flag POJK 11/POJK.03/2022 and other sector outsourcing or resilience rules for separate review before relying on a generic cloud clause.`,
    `CN01 production data hosted in Indonesia; CM01 in Malaysia or Singapore. Transfers only with UU PDP Art. 56 safeguards / PDPA s.129 conditions, a transfer register and 30 days prior notice of new subprocessors with a right to object and terminate with a pro-rata refund.`,
    `Hosting in Singapore for CN01 with documented Art. 56 safeguards, reporting support and a named, closed subprocessor list (General Counsel and DPO).`,
    `None`,
    `Unrestricted transfers to any country with no notice of new subprocessors.`,
    `General Counsel and DPO`,
    `any country; facilities; where required; subprocessor URL; no advance notice; only remedy; terminate without refund; Singapore; United States; India; Philippines; pro-rata refund`,
    `Provider will host CN01 production Customer Data in Indonesia and CM01 Customer Data in Malaysia or Singapore as stated in the Order Form. Provider may transfer Personal Data only with documented safeguards required by applicable law, a maintained transfer register, and 30 days prior notice of any new Subprocessor with Customer's right to object and terminate the affected Services with a pro-rata refund.`,
  ),
  ...issue(
    `P13`,
    `Use of Customer Content for AI and product improvement`,
    `The Group's customer, partner, pricing, stock and transaction data must not become training material or product-improvement input for a vendor. Aggregated operational telemetry is acceptable only when it cannot identify the Group, its partners or individuals. The highest-risk wording may sit in online terms rather than the MSA, so review the URL printout as part of the signed file.`,
    `No use of Customer Content to train or improve any model or product. Usage Data only in aggregated, de-identified form for service operation.`,
    `None`,
    `None`,
    `Any right to train models on Customer Content or Personal Data.`,
    `Not acceptable`,
    `train; machine learning; improve products; develop services; Customer Content; Personal Data; Usage Data; de-identified; aggregated; online terms; incorporated by URL`,
    `Provider must not use Customer Content, Customer Data or Personal Data to train, tune, test or improve any model, product or service. Provider may use Usage Data only in aggregated and de-identified form for operating, securing and improving the Services for Customer.`,
  ),
  ...issue(
    `P14`,
    `Exit, data return and transition`,
    `Exit rights determine whether the Group can leave safely after termination, breach or supplier failure. Fourteen days is not enough to export a production portal, data warehouse, logs and configuration while maintaining business continuity. Transition assistance should be available at contract rates because then-current professional services rates can become a practical penalty for leaving.`,
    `90 days to export in an open, documented format (CSV, JSON or Parquet for data; standard database dumps), deletion certificate afterwards; up to 6 months of transition assistance at contract rates.`,
    `60 days export window and transition assistance at contract rates for 3 months (Head of Legal).`,
    `None`,
    `None`,
    `General Counsel and CISO`,
    `14 days; standard export format; then deleted; professional services rates; then-current rates; transition assistance; deletion certificate; CSV; JSON; Parquet; database dump`,
    `For at least 90 days after expiry or termination, Provider will make Customer Data available for export in open, documented formats including CSV, JSON, Parquet and standard database dumps. Provider will provide reasonable transition assistance for up to six months at the rates in the applicable Order Form and will issue a deletion certificate after confirmed deletion.`,
  ),
  ...issue(
    `P15`,
    `Termination for convenience`,
    `The Group may need to exit after a strategic change, failed migration, insourcing decision or replacement project. Paying all remaining fees after a 90-day notice period is economically the same as having no convenience termination right. Finance must understand the maximum remaining commitment before any compromise is accepted.`,
    `After the first 12 months, termination for convenience on 90 days notice with no early termination fee.`,
    `Early termination fee up to 50% of the remaining Fees (CFO).`,
    `None`,
    `None`,
    `General Counsel and CFO`,
    `terminate for convenience; all Fees for remainder; immediately due; early termination fee; 50%; after first 12 months; 90 days notice; non-refundable`,
    `After the first 12 months of the Initial Subscription Term, Customer may terminate the affected Services for convenience on 90 days written notice. No early termination fee applies, and Customer remains responsible only for Fees accrued before the effective termination date.`,
  ),
  ...issue(
    `P16`,
    `Audit and assurance`,
    `Assurance reports reduce the need for intrusive audits, but they do not replace regulatory access or post-incident verification. For hosted platforms, SOC 2 Type II and ISO/IEC 27001 evidence should be available annually. The Group must retain an audit route where a regulator requires information or a Security Incident affects Customer Data.`,
    `SOC 2 Type II and ISO 27001 reports, plus a right to audit once a year on 30 days notice.`,
    `Reports, plus audits required by a Regulator and after a Security Incident (Head of Legal).`,
    `None`,
    `None`,
    `Head of Legal`,
    `SOC 2 Type II; ISO 27001; on request; on-site audit; regulator; security incident; once a year; 30 days notice; customer's cost; assurance report`,
    `Provider will provide current SOC 2 Type II and ISO/IEC 27001 reports annually on request. Customer may audit Provider once per year on 30 days notice, and additionally where required by a Regulator or after a Security Incident affecting Customer Data.`,
  ),
  ...issue(
    `P17`,
    `Assignment and change of control`,
    `Assignment rules protect the Group from being moved to a provider, affiliate or successor it did not diligence. A cloud provider's change of control can alter sanctions, data access, support quality, competition concerns and operational risk. The Group needs at least notice and a termination right if the provider is acquired by a competitor or unacceptable successor.`,
    `Mutual consent for assignment; either party may assign to an Affiliate or successor with notice; Customer may terminate without penalty if Provider comes under the control of a competitor.`,
    `Provider may assign to a successor with 30 days notice and Customer gets a termination right without fee (Head of Legal).`,
    `None`,
    `None`,
    `General Counsel`,
    `assign without consent; Affiliate; successor; merger; acquisition; change of control; competitor; consent not unreasonably withheld; 30 days notice; termination right`,
    `Neither party may assign the Agreement without the other's consent, except to an Affiliate or successor on written notice. Customer may terminate the affected Services without penalty if Provider undergoes a change of control involving a Customer competitor or a party that materially increases legal, security or sanctions risk.`,
  ),
  ...issue(
    `P18`,
    `Governing law and disputes`,
    `Dispute clauses affect enforcement strategy more than day-to-day operations. For CN01, the preferred position is Indonesian law and BANI arbitration in Jakarta; for CM01, Malaysian law and AIAC arbitration in Kuala Lumpur. Singapore law with SIAC arbitration seated in Singapore is an approved fallback, but enforcement of an arbitral award in Indonesia normally requires exequatur through the Central Jakarta District Court, and foreign court judgments are not enforceable in Indonesia in the same way.`,
    `CN01: Indonesian law, BANI arbitration in Jakarta. CM01: Malaysian law, AIAC arbitration in Kuala Lumpur.`,
    `Singapore law with SIAC arbitration seated in Singapore (Head of Legal). Note: enforcing the award in Indonesia needs an exequatur from the Central Jakarta District Court.`,
    `None`,
    `Foreign court jurisdiction (not arbitration) for CN01, because foreign court judgments are not enforceable in Indonesia.`,
    `Head of Legal`,
    `Singapore law; SIAC; BANI; AIAC; courts of Singapore; exclusive jurisdiction; foreign court; seat; Jakarta; Kuala Lumpur; exequatur; Central Jakarta District Court`,
    `For CN01, this Agreement is governed by Indonesian law and disputes are finally resolved by BANI arbitration seated in Jakarta. For CM01, this Agreement is governed by Malaysian law and disputes are finally resolved by AIAC arbitration seated in Kuala Lumpur.`,
  ),
  ...issue(
    `P19`,
    `Insurance`,
    `Insurance is a practical source of recovery and discipline for technology providers. If the agreement is silent, the Group has no contractual assurance that cyber, technology errors-and-omissions or professional liability cover exists when an incident occurs. A certificate is not a guarantee of payment, but it confirms minimum cover and supports vendor risk assessment.`,
    `Provider maintains cyber and technology errors-and-omissions insurance of at least USD 5,000,000 per claim and provides a certificate on request.`,
    `USD 2,000,000 per claim (Head of Legal).`,
    `None`,
    `None`,
    `Head of Legal`,
    `insurance; cyber; technology errors and omissions; professional liability; certificate; per claim; aggregate; not addressed; silent; insured`,
    `Provider will maintain cyber liability and technology errors-and-omissions insurance with limits of at least USD 5,000,000 per claim during the Subscription Term and for one year afterwards. Provider will provide certificates of insurance on Customer's reasonable request.`,
  ),
  `## 5. Indonesia and Malaysia law notes`,
  `Internal guidance, check current law before relying on it. These notes are not a substitute for matter-specific advice, but they explain why the playbook treats certain drafting positions as approval gates rather than stylistic preferences.`,
  `Language law. For Indonesian entities, bilingual execution remains the safest contracting practice. Law No. 24 of 2009 and Presidential Regulation No. 63 of 2019 require Indonesian language use in agreements involving Indonesian parties. Parties often agree that English prevails for interpretation, but do not accept an English-only contract or a waiver of language-law protections. The Nine AM decision from the West Jakarta District Court is not treated as a complete statement of all current law; it is treated as a risk signal that language defects can become litigation leverage.`,
  `Personal data transfers and breach timelines. Indonesia's UU 27/2022 requires personal data controllers and processors to manage processing, security, cross-border transfer safeguards and breach notification. Article 46 is the operational reason for requiring incident notice within 24 hours from awareness, because CN01 may need to notify affected data subjects and the authority within 3 x 24 hours. Article 56 is the operational reason for requiring a transfer register, safeguards and documented assessment before data moves outside Indonesia.`,
  `Malaysia PDPA. For Contoso Niaga Malaysia, the Personal Data Protection Act 2010 as amended should be checked for processor obligations, data protection officer requirements, breach notification and cross-border transfer restrictions. The playbook uses section 12B as the basis for a 72-hour notification planning assumption and section 129 as the transfer-control reference. Because commencement and subsidiary regulations can change, the reviewer must check current Malaysian rules before final approval.`,
  `Stamp duty. Indonesia generally uses fixed e-meterai for many commercial documents; the current fixed amount commonly applied is IDR 10,000, but Finance should confirm the current stamping process. Malaysia service agreements may attract ad valorem duty, often analysed at 0.5% depending on instrument type and current rules; Procurement must ask Finance or local counsel to check stamping cost before signature and before agreeing that the Malaysian subsidiary bears all duty.`,
  `Arbitration and enforcement. BANI in Jakarta is preferred for CN01 and AIAC in Kuala Lumpur for CM01. SIAC seated in Singapore is a pre-approved fallback only at Head of Legal level. If an award must be enforced in Indonesia, expect an exequatur process through the Central Jakarta District Court. Do not accept foreign court jurisdiction for CN01 as a substitute for arbitration without General Counsel review because foreign court judgments are not directly enforceable in Indonesia.`,
  `Regulated entities. This playbook is for the distribution group and its subsidiaries, not for a bank or insurer. If a deal supports financing, payment, lending, insurance, investment, e-wallet, regulated data hosting, or a regulated affiliate, flag OJK, Bank Indonesia, Bank Negara Malaysia and sector outsourcing or resilience rules before relying on this playbook alone. POJK 11/POJK.03/2022 is a flag for regulated financial-services contexts, not a blanket rule for every distribution contract.`,
  `## 6. Contract Review Record template`,
  {
    table: [
      [`Issue ID`, `Topic`, `Clause(s)`, `What the contract says`, `Verdict`, `Proposed redline`, `Approver`, `Status`],
      [`P01`, `Order of precedence and online terms`, ``, ``, ``, ``, ``, ``],
      [`P02`, `Contract language`, ``, ``, ``, ``, ``, ``],
      [`P03-P19`, `Add one row per reviewed issue`, ``, ``, ``, ``, ``, ``],
    ],
  },
  `Every review record must be saved with the contract file. Use the exact verdict labels used by Legal & Compliance: Meets standard, Within fallback 1, Within fallback 2, Beyond fallback: escalate, Red line, or Not addressed. If a single clause affects multiple issues, repeat the clause reference in each row so approvers can see the full risk pattern.`,
  `### Common vendor drafting tricks checklist`,
  `- Override clauses using 'notwithstanding' that reverse a more protective DPA, order form or schedule.`,
  `- Terms incorporated by URL, especially service terms, AI terms, acceptable use policies, support policies, security policies and subprocessor lists.`,
  `- Order-of-precedence clauses that rank negotiated terms last or make online terms prevail over signed documents.`,
  `- Notice or breach clocks that start at provider 'confirmation' instead of awareness.`,
  `- Sole and exclusive remedy language attached to service credits, support failures, data issues or indemnities.`,
  `- Broad excluded losses that remove data restoration, substitute services, remediation costs or regulator fines.`,
  `- Short export windows, vendor-standard export formats, deletion before migration validation, or transition assistance only at then-current rates.`,
  `- Auto-renewal notice periods that require action before Procurement's annual planning cycle.`,
  `- Price increase wording using 'greater of', list price resets, anniversary adjustments, or online price schedules that override a price hold.`,
  `- Subprocessor clauses that provide notice only by updating a website and give termination without refund as the only remedy.`,
  `## 7. Document control`,
  {
    table: [
      [`Version`, `Date`, `Owner`, `Change notes`],
      [`1.0`, `2023`, `Legal & Compliance`, `First cloud and SaaS contracting standards for Indonesian distribution operations; focused on term, price, liability and language law.`],
      [`2.0`, `2024`, `Legal & Compliance with Information Security`, `Added managed services, incident notification, audit, exit support and cross-border transfer review steps for regional deals.`],
      [`3.0`, `January 2026`, `Legal & Compliance with Procurement and Finance`, `Aligned approval matrix with listed-company delegation, updated price increase and renewal controls, and added Malaysia subsidiary guidance.`],
      [`3.1`, `July 2026`, `Legal & Compliance`, `Updated PDP and PDPA notes, clarified online terms red line, added AI training restriction, and confirmed P05 invoice-date fallback as Legal Counsel pre-approved.`],
    ],
  },
];

export const EMAIL_REQUEST = [
  `From: Charlotte Waltson, VP of Procurement <charlotte.waltson@contosoniaga.example>`,
  `To: Legal Counsel (Commercial) <legal.commercial@contosoniaga.example>`,
  `Cc: Lydia Bauer, Enterprise IT Architect <lydia.bauer@contosoniaga.example>; Siti Rahmawati, Head of Legal & Compliance <siti.rahmawati@contosoniaga.example>`,
  `Sent: Monday, 28 September 2026 09:05`,
  `Subject: Tailspin contract review needed by Friday 2 October for 1 November Portal Mitra start`,
  `Pagi Legal team,`,
  `We need your review of the Tailspin Cloud Services documents by Friday, 2 October, so we can still sign before the planned 1 November 2026 start date. The migration has become urgent after the September P1 outage on Portal Mitra. Lydia's team needs the Tailspin environment ready for build-out in November, with migration completed by 31 January 2027, otherwise we will miss the post-outage stabilisation plan agreed with Operations and Sales.`,
  `Attached are: (1) Tailspin Master Subscription and Managed Services Agreement, MSA v4.2 ASEAN dated 15 September 2026, including schedules; (2) Order Form TS-OF-2026-0417 for PT Contoso Niaga Nusantara Tbk; (3) Order Form TS-OF-2026-0418 for Contoso Niaga Malaysia Sdn. Bhd.; and (4) a PDF printout of the Tailspin Service Terms from their website. Please assume the acceptable use policy and subprocessor list are also incorporated by URL unless you tell us we need a dated copy.`,
  `Commercially, we have agreed USD 1,080,000 per year for CN01 and USD 144,000 per year for Malaysia, each for 36 months. Tailspin says the MSA is their standard ASEAN paper and largely non-negotiable. They also said they can discuss reasonable commercial points, but their counsel was clear that they do not want to reopen the liability, data or precedence structure. The Jakarta hosting commitment for CN01 and the price hold were hard-won in the Order Form Special Conditions, so please check that nothing in the MSA or online terms cuts across those points.`,
  `Can you please send us three outputs: first, the Contract Review Record against the cloud and managed services playbook; second, a short list of items that require escalation, with named approvers and why; and third, a draft email back to Tailspin that we can send by Thursday morning. If any item is a true red line, please make that clear early so I can manage expectations with the Steering Committee and Tailspin's account team.`,
  `Terima kasih,`,
  `Charlotte`,
];

export const EMAIL_VENDOR = [
  `From: Priya Raman, Senior Counsel APAC, Tailspin Cloud Services <priya.raman@tailspin-cloud.example>`,
  `To: Charlotte Waltson, VP of Procurement <charlotte.waltson@contosoniaga.example>`,
  `Sent: Friday, 25 September 2026 16:40`,
  `Subject: Tailspin Managed Cloud Platform documents for Contoso Niaga review`,
  `Dear Charlotte,`,
  `Thank you for the constructive commercial discussions this week. As agreed, I am sending the Tailspin Master Subscription and Managed Services Agreement, MSA v4.2 ASEAN dated 15 September 2026, the two Order Forms for PT Contoso Niaga Nusantara Tbk and Contoso Niaga Malaysia Sdn. Bhd., and a printout of our current Service Terms. The Service Terms are also available online and are updated periodically to reflect our evolving services, operational practices and product portfolio.`,
  `Our MSA is Tailspin's standard ASEAN terms used by hundreds of enterprise customers in the region. It is designed to provide a consistent operating model across our platform, support, security and data processing commitments. We can of course discuss reasonable commercial points, especially where they help implementation planning, invoicing administration or contact details. However, we do not expect to reopen the liability framework, data architecture, or precedence structure, as those positions are part of the regional service model and are applied consistently across customers.`,
  `I understand your team placed particular importance on Jakarta hosting for the Indonesian production environment and on fee certainty for the initial term. Those points are reflected in the Special Conditions to the relevant Order Form. We look forward to receiving any consolidated comments after your review and remain available for a call next week if useful.`,
  `Kind regards,`,
  `Priya`,
];
