import { CASE as C, SOURCE as S, FILES as F, REVIEW_UNITS as U, EVIDENCE as E, STATUS_LABELS, DESIGN_LABELS, OPERATING_LABELS } from '../model.mjs';

export const SCOPE = [
  '# Malaysian vulnerable-consumer readiness: scope and request',
  `## 1. Request received: ${C.snapshot}`,
  `From: ${C.author}, ${C.role}. To: Malaysian retail, service, risk and policy owners. Subject: scoped readiness evidence for Head of Compliance review and the internal Board Risk Management Committee (BRMC) paper. Entity: ${C.entity}; fictional licensed-bank treatment is assumed only for this training exercise.`,
  `Please prepare a source-cited review at the evidence cutoff of ${C.cutoff}. Head of Compliance will review the working register at ${C.review}. The internal BRMC paper is due ${C.paper}. These are bank planning dates, not regulator submission deadlines. The relevant legal effective date is ${C.effective}; do not substitute the source issue date, a project go-live or a committee date.`,
  'We need an honest account of what the supplied documents establish, not a certification. A carefully written policy can be approved without being implemented. Identify unavailable evidence and contradictions so owners can decide what to obtain and what to change. Do not silently convert a management assertion into a tested outcome.',
  'Return an analysis table, a downloadable Excel register and an unsigned Word review note using the supplied template. This request authorises preparation only: do not change source policies, contact customers or colleagues, initiate remediation, submit a regulatory return or send the committee paper.',
  '## 2. Entity and activity boundary',
  `${C.entity} serves retail customers through products, branches, a contact centre, representatives and outsourced agents. Its retail credit decisions use a production machine-learning assessment model. Its vulnerability programme covers different support needs without assuming that age, disability or another characteristic alone determines a customer outcome.`,
  `The bank distributes partner insurance and takaful products but does not underwrite them. Record the distinction between bank distribution support and an insurer or takaful operator's underwriting obligations. Retain a handoff owner for partner confirmation where relevant. ${C.sister} is a separately licensed sister entity in Indonesia; its policy and operating evidence are not proof for Malaysia.`,
  'The Bahasa Indonesia prompt is a language variant of this Malaysian case, not Indonesian legal validation. An Indonesian implementation requires its own OJK sources, entity boundary, effective dates and internal evidence. No Malaysian S/G classification or effective date should be copied into an Indonesian regulatory conclusion.',
  '## 3. Source boundary and review method',
  `File ${F.source} is an independently authored, scoped source-review brief with paraphrases and official paragraph/page locators. It is not the official policy document, legal advice or a substitute for counsel reading the authoritative PDF. The exercise deliberately reviews selected questions, not all FTFC obligations or every element of each paragraph.`,
  `Use only the attached inputs for this run. The ${C.predecessor} predecessor text is not provided, so every clause-by-clause change comparison is Unknown. Related policy texts are also not supplied; a reference to them cannot prove their requirements were reviewed. Do not browse or import current-law claims into this historical snapshot.`,
  'Read the complete policy including annexes, the evidence limitations and the steering minutes before deciding. A dated operating artifact may establish a limited activity without proving the entire enterprise compliant. Cite the official printed page and paragraph from the brief, the policy section and an evidence item ID for each judgement.',
  '## 4. Fixed review questions',
  { table: [['Key / class', 'BNM paragraph', 'Authored review question'], ...U.map((u) => [`${u.id} / ${u.type}`, u.para, u.question])] },
  '## 5. Classification rules, not answers',
  `Documented design labels: ${DESIGN_LABELS.join(', ')}. Approved means the relevant design has documented authority; Draft means approval is absent. Guidance and out-of-scope underwriting questions use N/A. The Board approval scope and explicit exclusions decide this dimension.`,
  `Operating evidence labels: ${OPERATING_LABELS.join(', ')}. Evidenced means supplied, dated, entity-relevant artifacts support the scoped question. Partial means some necessary elements are demonstrated. Not evidenced means no usable operating artifacts establish the required operation. Unverifiable means a specific assertion or dependency cannot be checked with the supplied records.`,
  `Readiness labels: ${STATUS_LABELS.join(', ')}. Covered requires approved design plus operating support for the scoped question. Partial requires approved design and incomplete operating support. Gap means an unapproved required design or no demonstrated operation. Unverified means a material assertion or related-source dependency remains unverifiable. Guidance noted and N/A are not mandatory failures.`,
  'Covered means a match to this scoped question and the supplied Malaysian evidence at the cutoff, not legal compliance. Future plans, proposed expenditure and advertised channels are not proof of availability. An expired artifact cannot establish current authority. An approved design does not cure missing operating evidence. Keep the two assessment dimensions visible.',
  '## 6. Ownership, actions and review control',
  { table: [['Review key', 'Responsible role'], ...U.map((u) => [u.id, u.owner])] },
  'Use these accountable roles, not invented individual assignees. Suggested actions must describe the missing evidence or control and the decision needed. Leave due targets blank or label them proposed and pending owner/Head of Compliance agreement. Do not fabricate pass marks, remediation volumes, deployment promises or approved budgets.',
  'Before the paper is used, reconcile the register with the source artifacts, check all classifications and compare the Word counts to the Excel Summary. Keep the original inputs unchanged. Save outputs in an authorised work folder, apply the organisation’s required label, and obtain Head of Compliance sign-off outside this drafting exercise.',
];

const SOURCE_NOTES = {
  R01: 'Focus on identifying relevant needs, translating them into policies and making those policies known to the people who must use them. A communication artifact and the underlying assessment answer different parts of this question. This brief does not prescribe a particular assessment form, numerical survey threshold or bank-wide certification method.',
  R02: 'The design question concerns whether products and services reflect vulnerable-consumer needs rather than treating those needs as a service exception after launch. A signed product decision can be relevant to that question. It does not establish that every product has been reviewed or that later operating outcomes are satisfactory.',
  R03: 'Review pricing and fee considerations alongside safeguards against adverse consequences for vulnerable consumers. Individual relief activity is not interchangeable with a considered review of price structures. This paraphrase sets no fee cap, waiver quota or automatic entitlement; the reviewer must keep bank-selected arrangements distinct from the source standard.',
  R04: 'The concern is preventing predatory treatment, not merely having a reassuring statement in a policy. The review asks for evidence behind an operating assertion. A missing report creates an evidence limitation; it does not establish that predatory conduct occurred or justify an allegation against any real institution.',
  R05: 'The paragraph addresses due care where machine learning is used for credit assessment in relation to vulnerable consumers. Consider the actual production use, not just a proposed model-governance document. The exercise does not invent a required mathematical fairness metric, pass mark or regulator-approved model-validation technique.',
  R06: 'Training concerns personnel who deal with vulnerable consumers, including relevant representatives and agents. Ask what the training prepares people to do and which populations it reaches. A bank may require skills assessment as its own control; that internal rule must not be attributed to BNM as a specified examination score.',
  R07: 'Recording a customer’s needs and making useful information available to relevant service personnel are connected but separate considerations. A proposed system field is not an operating record, and a stored record is not necessarily accessible at handoff. Apply appropriate information handling rather than assuming unrestricted access is required.',
  R08: 'Personnel need sufficient flexibility to respond sensibly to customer circumstances rather than being constrained by an inflexible standard process. Consider the authority available to staff, representatives and agents and whether its use is demonstrated. Flexibility does not remove accountability or authorise bypassing identity, security or other applicable safeguards.',
  R09: 'Adaptability concerns how service is delivered for the customer’s needs. More time, an appropriate callback or a suitable explanation may illustrate the bank’s response, without being an exhaustive prescribed menu. Distinguish a genuinely deployed service adaptation from unrelated technology plans described in the same programme.',
  R10: 'Consumers need accessible information about where and how to obtain assistance. Availability and accuracy matter together: a leaflet can reach customers yet advertise a route that does not exist. This review does not assume that a particular digital platform is mandatory or that web publication alone satisfies all needs.',
  R11: 'Look across the customer lifecycle at communication clarity, periodic evaluation of effectiveness and awareness of available channels. Approved wording is different from evidence that communications work. Do not create a regulator-specified testing frequency or claim a future comprehension exercise has already occurred at the evidence cutoff.',
  R12: 'Monitoring and evaluation should inform improvements in outcomes for vulnerable consumers. A list of proposed measures is not an operating return, and a funding request is not a completed improvement. This scoped question does not prescribe a dashboard vendor, expenditure amount or regulator-mandated number of indicators.',
  R13: 'Review this policy document in conjunction with relevant related requirements. This creates an important source dependency: a work plan or list of titles cannot establish the content of absent texts. The exercise supplies no complete related-policy set, so the reviewer must preserve that limitation rather than inventing a cross-policy legal conclusion.',
  R14: 'The governance question concerns clear accountability, appropriate policies and arrangements that support people assisting vulnerable consumers. Governance authority can be evidenced independently of every operating control. Do not treat a Board policy approval as blanket approval of excluded annexes, future expenditure or the quality of later customer outcomes.',
  R15: 'This guidance invites consideration of multiple communication channels in supporting vulnerable consumers. Treat it as a discussion of suitable approaches, not a mandatory requirement to launch WhatsApp, video relay or every possible channel. Published availability claims should still be accurate under the separate communication review questions.',
  R16: 'This guidance concerns a longer free-look arrangement for insurers and takaful operators. The fictional bank is a distributor, not the underwriter. Keep the underwriting applicability decision separate from a distribution handoff to the responsible partner for Legal confirmation; do not erase the customer-support interface or invent a free-look period.',
};

export const SOURCE_BRIEF = [
  '# Reviewed-source brief: Fair Treatment of Financial Consumers',
  '## 1. Authorship, authority and limited use',
  `Independent training brief prepared for ${C.entity} at ${C.cutoff}. All bank facts are fictional. The source is the real ${S.issuer} policy document ${S.title}, reference ${S.reference}, issued ${C.issued}. The explanations below are original authored PARAPHRASES, not quotations, official translations or regulator-endorsed interpretations.`,
  `The official PDF has ${S.pdfPages} PDF pages; its printed page number is the PDF page number minus one. Each review unit below gives both locators. Lawyers must consult the official PDF for authoritative wording and full context. This brief intentionally does not reproduce the full document, regulator logos or letterhead.`,
  'Official source URL (wrapped for reading; join the two lines without spaces):',
  'https://www.bnm.gov.my/documents/20124/938039/',
  'pd-ftfc-mar24.pdf',
  '## 2. Dates, standards and predecessor',
  `Paragraph 4.1 provides a default effective date of ${C.issued}, with exceptions ${S.exceptionParagraphs} effective ${C.effective}. All review units below fall within those exceptions. The document issue date is not their effective date. The internal committee timetable in file 01 is not a BNM reporting deadline.`,
  `Paragraph 5.2 distinguishes S standards (mandatory) from G guidance. Paragraph 6.2 supersedes the predecessor issued ${C.predecessor}. The predecessor text is absent, so clause-by-clause New, Changed or Unchanged classifications cannot be established. Record Unknown rather than assuming all selected S paragraphs introduce new duties.`,
  '## 3. Selected review units: authored paraphrases',
  'These review units are a controlled sample, not an exhaustive legal inventory. Read each question with its source paragraph and the limitations below. The classifications assess the supplied evidence for the question, not the whole bank’s compliance with the paragraph.',
  ...U.flatMap((u) => [
    `## ${u.id}. ${u.type} ${u.para} | printed p.${u.page} | PDF p.${u.page + 1}`,
    `PARAPHRASE / review question: ${u.question}`,
    SOURCE_NOTES[u.id],
    `Locator: ${S.reference}, ${u.type} ${u.para}; effective ${C.effective} under paragraph 4.1; issued ${C.issued}.`,
  ]),
  '## 4. Limits on legal and geographical conclusions',
  `No related-policy texts for the paragraph 16.28 cross-review are bundled. No Indonesian legal conclusion follows from this source. The OJK title supplied in the sister-entity SOP is contextual only. This ${C.snapshot} snapshot makes no assertion about subsequent amendments, present-day law, holiday calendars or regulatory filing obligations outside its stated scope.`,
];

export const READINESS = [
  '# Readiness evidence index and attached artifact summaries',
  `## 1. Custody and cutoff: ${C.cutoff}`,
  `Prepared by ${C.author}, ${C.role}, for ${C.entity}. This document contains the exercise’s supplied artifact extracts and proof summaries. References below are internal fictional references, not links to undisclosed tenant documents. No customer-level data, recordings or real signatures are included. An artifact expressly listed as missing is not implicitly attached elsewhere.`,
  'Owner-certified summaries describe the supplied records with enough context for the scoped exercise. Approval and issue metadata concern the named artifact only. An approved work plan remains a plan; a signed statement can still lack corroboration. Do not fill blank evidence with likely practice or treat a historical record as current without checking its validity.',
  '## 2. Artifact index: one record per E-number',
  ...E.flatMap((e) => [
    `### ${e.id}. ${e.ref}`,
    `Entity: ${e.entity}. Owner: ${e.owner}. Approval/version: ${e.approval}. Record date: ${e.date}.`,
    `Actually attached: ${e.attached}`,
    `Missing / not attached: ${e.missing}`,
    `Validity and reliance boundary: ${e.validity}`,
  ]),
  `## 3. Steering Minutes: ${C.steering}`,
  'Meeting reference MY-VC-STEER-03. Chair: Chief Customer Experience Officer. Attendees: Retail Operations, Digital Channels, Communications, Conduct Risk, Finance representative and Compliance Advisory. These are supplied internal minutes extracts, not Board budget approval. Actions below remain open at the evidence cutoff.',
  '### M1. Assistance-channel correction',
  'Communications confirmed that the printed leaflet contains phone and branch assistance details alongside WhatsApp and video-relay promises. Digital Channels confirmed that neither additional service has a provider or a funded deployment and neither is available in 2025. The current service options are phone and branch assistance. A leaflet claim must not override this explicit availability record.',
  'Open action: Head of Customer Communications to remove the unsupported wording, arrange a controlled correction and supply evidence of replacement distribution. No completed correction or signed-off replacement leaflet is in this pack. The committee did not approve a channel launch or a spending allocation. Contact-centre handling flexibility is separate from launching new channels.',
  '### M2. CRM timing and interim proposal',
  `Technology confirmed CR2291 still targets ${C.crm}. Branch Operations presented only a spreadsheet schema proposal, without completed records or an implemented handoff/access mechanism. The programme must not describe the schema as a live interim solution. No accelerated delivery date was approved.`,
  'Open action: the CRM and Branch Operations owner to propose a workable interim arrangement, obtain required approvals and bring operating evidence. Any target proposed in the review register is for owner agreement, not a commitment recorded in these minutes.',
  '### M3. Outcomes dashboard decision',
  `Conduct Risk presented the ${C.budgetLabel} dashboard proposal. The Finance representative confirmed that the CFO had not approved it. No operating outcome monitoring return or completed evaluation was tabled. The minutes record a decision request, not expenditure authorisation or evidence of completed implementation.`,
  'Open action: Conduct Risk to identify a proportionate operating approach and seek a funding decision where necessary. Compliance asked that the committee paper clearly distinguish a proposed resource request from an approved control and disclose any monitoring evidence still unavailable.',
  '## 4. Reconciliation note',
  'The evidence pack preserves contradictions rather than editing them away. Treat approval dates, deployment records, expiry notices and the explicit steering decisions as separate facts. Do not delete inconvenient records or silently assume a newer approval. Where the source does not permit a conclusion, identify what the responsible owner must provide before the conclusion can be reconsidered.',
];

export const TEMPLATE = [
  '# BRMC paper: vulnerable-consumer readiness',
  'UNSIGNED REVIEW DRAFT — template only; no committee endorsement.',
  `## 1. Paper control and decision sought`,
  `Entity: ${C.entity}. Prepared by: ${C.author}, ${C.role}. Evidence cutoff: ${C.cutoff}. Head of Compliance review: ${C.review}. Internal BRMC paper deadline: ${C.paper}. These bank dates are not regulator filing deadlines.`,
  'Decision sought: review the scoped evidence position, identify unresolved exposures and agree who should return with evidence or an approval proposal. This paper does not authorise customer communications, policy amendments, expenditure or remediation execution. Keep the completed note within two pages; use short paragraphs and a compact action table.',
  '## 2. Scope and source limitation',
  `State the retail-bank activities assessed, the selected S/G review units and the ${C.effective} legal effective date. Explain that the source brief is authored paraphrase, not legal authority, and that Covered means only a scoped evidence match. Exclude Indonesian operating evidence and bank-as-underwriter assumptions.`,
  'Identify the absent predecessor and related-policy texts. State that clause-level changes cannot be established and that this is a historical snapshot, not an exhaustive current-law assessment. Preserve limitations from the verified register even if the executive summary becomes less reassuring.',
  '## 3. Summary of the verified register',
  { table: [['Measure', 'Populate from verified Excel register'], ['All review rows / mandatory S / G', '[linked register totals]'], ['Readiness counts', '[each register status, guidance separate]'], ['Documented design / operating evidence', '[separate distributions]']] },
  'Reconcile every number to the Excel Summary and its source status column. Do not replace calculated totals with a judgemental overall readiness percentage. Explain the difference between approved design and demonstrated operation; avoid describing the bank as compliant.',
  '## 4. Priority risks, actions and decisions',
  { table: [['Review key / source', 'Exposure and evidence needed', 'Owner / proposed target / decision'], ['[key and citations]', '[concise issue, no invented incident]', '[role; pending agreement]']] },
  'Prioritise Gap and Unverified items, then material Partial items. Distinguish obtaining missing proof from implementing a missing control. Preserve the partner distribution handoff. Do not invent numerical remediation commitments, approved delivery dates or new regulatory obligations.',
  '## 5. Resources and timeline',
  `Separate ${C.budgetLabel} proposed expenditure, pending CFO decision, from any approved resources actually evidenced. Keep planned technology milestones distinct from the legal effective date. Do not imply that a milestone after that date has been accepted by the regulator.`,
  '## 6. Review and sign-off',
  'Head of Compliance: [blank — unsigned]. Review decision: [pending]. Date: [blank]. Committee endorsement: [not sought by this draft]. The human reviewer must check source citations, evidence limitations and saved files before agreeing the final text. No signature, approval or distribution should be simulated.',
];
