export const EMAIL_REQUEST = [
  `# Email`,
  {
    table: [
      [`Dari`, `Dewi Lestari, Corporate Secretary`],
      [`Kepada`, `Manager, Corporate Secretary Office`],
      [`Dikirim`, `Senin, 5 Oktober 2026 pukul 07:48 WIB`],
      [`Subjek`, `[RAHASIA] Proyek Kutub – draf Usulan Keputusan Direksi untuk rapat 7 Oktober`],
    ],
  },
  `Pagi, mohon segera susun draf **Usulan Keputusan Direksi** untuk Proyek Kutub memakai template terlampir. Target saya adalah draf lengkap sudah masuk ke saya paling lambat **Selasa, 6 Oktober 2026 pukul 10.00 WIB**, sehingga masih ada waktu legal scrub dan angka dapat dikunci sebelum rapat Direksi **Rabu, 7 Oktober 2026 pukul 09.00 WIB**. Setelah disetujui Direksi, paket untuk Dewan Komisaris harus bisa diedarkan paling lambat **Jumat, 9 Oktober 2026** untuk agenda **Rabu, 14 Oktober 2026**.`,
  `Gunakan urutan bagian persis seperti template. Jangan membuat struktur baru, jangan menggabungkan bagian yang pemiliknya berbeda, dan jangan mengisi dengan asumsi sendiri. Dasarnya hanya input divisi yang saya kirimkan bersama email ini. Apabila ada perbedaan angka atau posisi antar divisi, tampilkan keduanya apa adanya dan beri tanda **[KONFLIK]** di kalimat pertama bagian terkait. Apabila pemilik bagian belum menyerahkan input, beri tanda **[PERLU KONFIRMASI]** dan sebutkan nama divisinya. Semua kekosongan lain yang tidak boleh masuk ke naskah edaran masukkan pada halaman terakhir dengan judul **Hal Terbuka — Untuk Corporate Secretary – hapus sebelum diedarkan**.`,
  `Mohon pastikan bagian keputusan mencantumkan seluruh condition precedent dari Legal, bukan hanya persetujuan utama. Saya tidak ingin ada CP yang hilang dari resolusi Direksi karena dokumen ini akan menjadi dasar sirkulasi ke Dewan Komisaris dan komunikasi ke pemegang saham utama. Untuk subjek email, agenda, dan nama folder, tetap gunakan kode **Proyek Kutub**; jangan memakai nama target pada subject line. Insider list sudah dibuka dan trading blackout berlaku untuk seluruh pihak yang menerima paket ini sampai keterbukaan informasi dilakukan.`,
  `Catatan penting: Human Capital belum menyerahkan bagian SDM. Bu Sri janji kirim Selasa siang, jadi untuk saat ini bagian tersebut harus tetap diberi **[PERLU KONFIRMASI] Human Capital**. Jangan mengambil alih dari Operasi meskipun ada komentar mengenai jumlah karyawan dan overlap posisi.`,
  `Lampiran input divisi yang sudah tersedia:`,
  {
    table: [
      [`No.`, `Dokumen`, `Tanggal`, `Pemilik`],
      [`1`, `Project Kutub – Strategic Rationale (v2)`, `28 September 2026`, `Strategy & Business Development`],
      [`2`, `Proyek Kutub – Kajian Operasional dan Rencana Integrasi 100 Hari`, `30 September 2026`, `Operasi`],
      [`3`, `Proyek Kutub – Ringkasan Hasil Due Diligence Hukum dan Perpajakan serta Persetujuan yang Diperlukan`, `1 Oktober 2026`, `Legal dan Pajak`],
      [`4`, `Project Kutub – Transaction Structure, Valuation and Funding (v3, supersedes v2 of 18 Sep)`, `2 Oktober 2026`, `Keuangan`],
      [`5`, `Proyek Kutub – Kajian Risiko Awal (v1)`, `4 September 2026`, `Risk Management`],
    ],
  },
  `Terima kasih. Tolong prioritaskan bahasa yang rapi, ringkas, dan defensible untuk Direksi; isu teknis tetap dapat ditaruh dalam lampiran atau Hal Terbuka bila belum siap diedarkan.`,
];

export const TEMPLATE = [
  `# PT Fabrikam Logistik Tbk`,
  `# USULAN KEPUTUSAN DIREKSI`,
  {
    table: [
      [`Butir`, `Keterangan`],
      [`Nomor`, `UKD-0xx/DIR/FLOG/X/2026`],
      [`Tanggal`, `[tanggal dokumen]`],
      [`Kepada`, `Direksi PT Fabrikam Logistik Tbk`],
      [`Dari`, `[pemilik agenda / Corporate Secretary Office]`],
      [`Perihal`, `[judul transaksi / keputusan yang dimohonkan]`],
      [`Klasifikasi`, `RAHASIA – Informasi Orang Dalam`],
      [`Lampiran`, `Dokumen pendukung dari divisi, laporan penilai independen, rancangan keputusan, dan matriks persetujuan`],
    ],
  },
  `Dokumen ini digunakan untuk meminta persetujuan Direksi atas transaksi atau tindakan korporasi material. Main body maksimum **8 pages**, tidak termasuk lampiran. Semua figures dalam **Rp miliar** dengan **1 decimal** where needed, dan setiap angka harus menyebutkan sumber divisi atau dokumen pendukung. Jika ada perbedaan input antar divisi, drafter wajib menandai **[KONFLIK]** dan tidak memilih salah satu angka tanpa arahan Corporate Secretary.`,
  `## 1. Ringkasan Eksekutif`,
  `Pemilik bagian: Drafter (Corporate Secretary Office)`,
  `> Instruksi: Maksimum 1 halaman. Ringkas tujuan keputusan, pihak transaksi, nilai, sumber dana, persetujuan kunci, kondisi pendahuluan, dan rekomendasi. Tulis isu yang belum selesai secara eksplisit.`,
  `## 2. Latar Belakang dan Rasional Strategis`,
  `Pemilik bagian: Strategy & Business Development`,
  `> Instruksi: Jelaskan market context, strategic fit, alternatif yang dipertimbangkan, rationale build versus buy, dan kontribusi terhadap strategi jaringan FLOG. Hindari angka valuasi kecuali berasal dari Finance.`,
  `## 3. Struktur dan Nilai Transaksi`,
  `Pemilik bagian: Keuangan`,
  `> Instruksi: Uraikan objek transaksi, persentase saham, pihak penjual, locked-box date, price mechanism, escrow, dan tabel jembatan EV ke harga. Pisahkan enterprise value, equity value, dan harga porsi saham.`,
  `## 4. Analisis Keuangan dan Pendanaan`,
  `Pemilik bagian: Keuangan`,
  `> Instruksi: Sajikan impact terhadap kas, pinjaman, covenant, leverage, materiality test, sensitivity, dan kesimpulan fairness opinion. Jelaskan sumber pendanaan dan syarat bank secara ringkas.`,
  `## 5. Hasil Due Diligence Hukum dan Perpajakan`,
  `Pemilik bagian: Legal dan Pajak`,
  `> Instruksi: Cantumkan scope DD, adviser, temuan utama, risiko pajak, izin, kontrak material, kepatuhan lingkungan, dan mitigasi. Pisahkan temuan yang menjadi CP dan yang hanya menjadi covenant atau monitoring item.`,
  `## 6. Operasional dan Rencana Integrasi`,
  `Pemilik bagian: Operasi`,
  `> Instruksi: Jelaskan footprint site, fleet, IT/WMS, operational synergies, capex backlog, service KPI, dan rencana integrasi 100 hari. Tandai klaim yang membutuhkan validasi Finance atau Legal.`,
  `## 7. Dampak terhadap SDM`,
  `Pemilik bagian: Human Capital`,
  `> Instruksi: Isi headcount, retention, perubahan organisasi, industrial relations, komunikasi karyawan, dan estimasi biaya SDM. Jika belum ada input Human Capital, tulis [PERLU KONFIRMASI].`,
  `## 8. Analisis Risiko dan Mitigasi`,
  `Pemilik bagian: Risk Management`,
  `> Instruksi: Sajikan risk register dengan likelihood, impact, rating, mitigasi, owner, dan residual risk. Pastikan data yang stale dibanding input terbaru ditandai untuk diperbarui.`,
  `## 9. Kepatuhan dan Persetujuan yang Diperlukan`,
  `Pemilik bagian: Legal dan Corporate Secretary`,
  `> Instruksi: Cantumkan persetujuan Anggaran Dasar, pemegang saham utama, OJK/POJK, KPPU, keterbukaan informasi, benturan kepentingan, dan jadwal sirkulasi ke Dewan Komisaris.`,
  `## 10. Rekomendasi dan Usulan Keputusan Direksi`,
  `Pemilik bagian: Drafter (Corporate Secretary Office)`,
  `> Instruksi: Tarik kesimpulan dari bagian sebelumnya dan rumuskan keputusan yang dapat langsung ditandatangani. Daftar persyaratan pendahuluan (CP) lengkap wajib masuk ke batang tubuh keputusan.`,
  `## Usulan Keputusan`,
  `Formula dasar: **DIREKSI MEMUTUSKAN:** 1. Menyetujui [transaksi] dengan syarat [seluruh CP]; 2. Memberikan kuasa kepada Direktur Utama dan/atau Direktur Keuangan untuk menandatangani dokumen transaksi; 3. Menginstruksikan Corporate Secretary melakukan pemenuhan keterbukaan informasi dan koordinasi persetujuan; 4. Menetapkan bahwa keputusan berlaku sejak tanggal ditandatangani.`,
  {
    table: [
      [`Jabatan`, `Nama`, `Tanda tangan`, `Tanggal`],
      [`Direktur Utama`, `[●]`, `[●]`, `[●]`],
      [`Direktur Keuangan`, `[●]`, `[●]`, `[●]`],
      [`Corporate Secretary`, `[●]`, `[●]`, `[●]`],
    ],
  },
  `Lampiran: dokumen pendukung dari divisi.`,
];

export const INPUT_STRATEGY = [
  `# Project Kutub – Strategic Rationale (v2)`,
  {
    table: [
      [`Date`, `28 September 2026`],
      [`From`, `Aditya Nugroho, VP Strategy & Business Development`],
      [`To`, `Direktur Utama, Direktur Keuangan, Corporate Secretary`],
      [`Classification`, `Strictly Confidential – Project Kutub`],
    ],
  },
  `## Executive view`,
  `Project Kutub is a strategic entry point for PT Fabrikam Logistik Tbk into national cold-chain logistics at a scale that would be difficult to replicate organically within the current planning horizon. The target, PT Coho Rantai Dingin, operates **11 cold storage sites** across Cikarang, Surabaya, Medan, Makassar and other commercial corridors, supported by **420 reefer trucks** and a customer base in pharmaceuticals, frozen food and modern grocery distribution. Our view is that the business gives FLOG a credible temperature-controlled platform, not merely additional warehouse capacity.`,
  `Indonesia's cold-chain market is becoming more institutional. Pharma principals are tightening Good Distribution Practice requirements, national frozen-food brands are shifting from distributor-owned depots to outsourced multi-temperature logistics, and e-grocery operators need reliable same-day replenishment from urban cold nodes. The demand pattern is less about headline volume and more about compliance, route density, temperature traceability and the ability to serve Java and selected outer-island hubs under one operating standard. These are areas where FLOG has network discipline but limited cold-chain depth today.`,
  `## Strategic fit with FLOG`,
  `The fit is strongest in three areas. First, Cikarang and Surabaya overlap with FLOG's existing dry logistics hubs, allowing shared yard management, security, line-haul planning and customer-facing account management. Second, FLOG already serves several food and healthcare-adjacent customers in ambient logistics; Kutub would let us offer a single logistics solution where the customer has both ambient and chilled lanes. Third, FLOG's procurement and maintenance scale can reduce unit cost for tyres, fuel, insurance, telematics and refrigeration servicing while preserving the target's specialist operating procedures.`,
  `There is also a defensive logic. Several FLOG customers have started asking whether we can manage chilled, frozen and ambient flows under one governance model. If we remain only an ambient network operator, our role can be pushed down to commodity trucking while competitors own the temperature-controlled customer relationship. Coho already has operating references with regulated customers and food principals, which would take FLOG a long time to reproduce through greenfield development. The acquisition therefore protects share of wallet in existing accounts as much as it opens a new vertical.`,
  `The transaction is valued at around **IDR 1.9 trillion**, which we believe is justified by the scarcity of scaled Indonesian cold-chain platforms and the competitive process run by the seller. In Bahasa terms, Strategy views this as a valuation of about **Rp1,9 triliun** for a platform asset, not a single-site warehouse roll-up. The key strategic question for Direksi is therefore whether FLOG should secure control influence now or continue building incrementally while competitors lock up scarce compliant assets.`,
  `## Synergy target by year 3`,
  `Strategy proposes a synergy target of **Rp45 miliar** by year **3**. This estimate is directional and should be validated by Finance and Operations before being used in the board paper. The largest early benefit is not headcount reduction but network yield: filling backhaul lanes, consolidating procurement, and reducing duplicated third-party cold storage in overlapping locations.`,
  {
    table: [
      [`Synergy lever`, `Year 3 run-rate`, `Basis`],
      [`Shared sites and yard services`, `Rp15 miliar`, `Cikarang and Surabaya overlap; shared security, utilities coordination and site administration`],
      [`Routing and backhaul optimisation`, `Rp18 miliar`, `Better reefer utilisation on Java lanes and selected Medan/Makassar flows`],
      [`Procurement and maintenance`, `Rp12 miliar`, `Fuel, tyres, refrigeration maintenance, telematics and insurance scale`],
      [`Total`, `Rp45 miliar`, `To be validated in integration plan`],
    ],
  },
  `## Alternatives considered`,
  `We assessed a pure build strategy. Building sites gives full design control, but land, permitting, BPOM-ready processes, WMS configuration, and pharma customer qualification would create a long ramp-up. A build programme also does not solve the immediate need for reefers, trained cold-chain supervisors and established customer audits. In our view, build remains useful for selective infill capacity after acquisition, not as the primary route to market.`,
  `We also reviewed two potential acquisition alternatives. PT Northwind Frozen Nusantara had attractive east Java capacity but limited pharma exposure and a site condition that would require heavy remediation. PT Tailspin Cold Express had a modern fleet but weaker site ownership, higher customer churn, and less overlap with FLOG's network. Neither provided the same combination of national footprint, regulated-customer credibility and integration potential as Coho.`,
  `A commercial partnership was considered as a lower-commitment option. That route would reduce execution burden, but it would not give FLOG control over service quality, investment timing, account allocation or the data needed for integrated customer offers. It would also leave the seller free to partner with a competitor or change commercial terms after FLOG helped develop demand. Strategy therefore views partnership as an interim commercial tactic, not a substitute for ownership in a scarce platform.`,
  `## Strategic recommendation`,
  `Subject to Finance confirming valuation and funding, Legal confirming CPs and approvals, and Operations finalising the 100-day integration plan, Strategy recommends proceeding with Project Kutub. The board paper should present this as a platform acquisition to accelerate FLOG's move into compliant cold-chain logistics and to protect our relevance with pharma, frozen food and e-grocery customers that increasingly expect multi-temperature network solutions.`,
  `The recommendation is not to integrate everything on day one. The value case depends on retaining specialist cold-chain discipline while applying FLOG governance, procurement, capital allocation and customer coverage. Strategy recommends that the Direksi decision require a post-completion integration steering committee with Finance, Operations, Strategy, Legal, Risk and Human Capital participation, so that synergy pursuit does not undermine customer assurance or regulatory compliance.`,
];

export const INPUT_FINANCE = [
  `# Project Kutub – Transaction Structure, Valuation and Funding`,
  {
    table: [
      [`Date`, `2 October 2026`],
      [`From`, `Maya Anggraini, Direktur Keuangan`],
      [`Version`, `v3, supersedes v2 of 18 Sep`],
      [`Classification`, `Strictly Confidential – Project Kutub`],
    ],
  },
  `## Purpose and version note`,
  `This memorandum sets out Finance's current view on transaction structure, valuation, funding, materiality and financial conditions for Project Kutub. It supersedes the earlier Finance v2 circulated on 18 September following receipt of the updated bid process letter, the reviewed interim balance sheet of FLOG at 30 June 2026, the audited 2025 financials of PT Coho Rantai Dingin, and the draft fairness opinion materials from KJPP Lucerne dan Rekan. All amounts are stated in IDR billion unless noted otherwise.`,
  `The proposed transaction is the acquisition by PT Fabrikam Logistik Tbk of a **60%** equity interest in PT Coho Rantai Dingin from Blue Yonder Capital Fund II and the founder sellers. The seller has run a competitive process. Our non-binding LOI price of **IDR 940 billion** dated **12 August 2026** was increased after that process and after management concluded that the strategic platform value and competitive tension supported the revised price. The revised price is the basis for the board paper and for the materiality analysis below.`,
  `## Valuation bridge`,
  `Finance values the target using audited 2025 EBITDA and an enterprise value multiple. The audited 2025 EBITDA used for the bridge is **214**. We have not used any higher management EBITDA number for the transaction valuation. Target revenue for 2025 was **1,860**. Net debt is deducted to derive equity value, and the purchase price reflects only the **60%** stake to be acquired.`,
  {
    table: [
      [`Item`, `Calculation`, `IDR billion`],
      [`Audited 2025 EBITDA`, `As audited`, `214`],
      [`Enterprise value`, `8.9x audited 2025 EBITDA`, `1,905`],
      [`Less: net debt`, `Debt less cash at locked-box reference`, `(205)`],
      [`Equity value 100%`, `Enterprise value less net debt`, `1,700`],
      [`Price for 60% stake`, `60% of equity value`, `1,020`],
    ],
  },
  `The enterprise value multiple of **8.9x** is within the observable range for scarce temperature-controlled logistics platforms in Indonesia when adjusted for scale, growth, customer quality and capex backlog. The implied 100% equity value is **IDR 1,700 billion**, and the agreed price for the stake is **IDR 1,020 billion**.`,
  `## Locked-box and escrow`,
  `The transaction is proposed on a locked-box basis with a locked-box date of **30 June 2026**. Leakage covenants must be included in the share purchase agreement, and any permitted leakage should be listed exhaustively. Finance supports Legal's proposed escrow of **5%** of the purchase price, equal to **IDR 51 billion**, to cover the identified tax exposure of **IDR 38 billion** and related costs. The escrow mechanics should allow claims for tax assessments, penalties and interest arising from pre-locked-box periods.`,
  `The locked-box approach is acceptable to Finance only if the SPA includes robust undertakings on no leakage, ordinary-course conduct, information access and a clear indemnity claim process. Any management fee, dividend, related-party payment, asset disposal or seller-side cost charged to the target after the locked-box date should be treated as leakage unless expressly permitted. Finance will require a closing certificate from the sellers and a bring-down confirmation from management before funds are released.`,
  `## Funding plan`,
  `Funding is proposed as a mix of internal cash and acquisition debt. This balances balance-sheet discipline with the need to preserve liquidity for ongoing fleet replacement and site expansion. PT Bank Woodgrove Indonesia has provided indicative terms for the loan tranche subject to final credit approval, customary conditions and completion of legal documentation.`,
  {
    table: [
      [`Funding source`, `Amount`, `Share of price`, `Comment`],
      [`Internal cash`, `408`, `40%`, `Available corporate cash; preserves covenant headroom`],
      [`Bank loan – PT Bank Woodgrove Indonesia`, `612`, `60%`, `Acquisition facility; final documentation required`],
      [`Total`, `1,020`, `100%`, `Matches purchase price`],
    ],
  },
  `On a pro-forma basis, FLOG net debt/EBITDA increases to **2.3x** compared with current **1.6x** and the covenant of **3.0x**. Finance considers this acceptable provided no additional debt-funded M&A is committed before completion and the integration capex profile is separately approved. Treasury should also confirm drawdown timing against the signing and completion timetable.`,
  `The facility from PT Bank Woodgrove Indonesia should be documented with prepayment flexibility, no dividend lock-up beyond normal covenant protection, and the ability to refinance once the acquisition has stabilised. Finance does not recommend using all-cash funding because it would reduce liquidity for existing fleet renewal, working capital seasonality and the capex programme that Operations has identified. The mix above also preserves discipline: management will need to demonstrate synergy delivery and cash conversion before requesting further growth capital.`,
  `## Materiality and regulatory financial analysis`,
  `The transaction value for the materiality test is the purchase price of **IDR 1,020 billion**. FLOG equity at **30 June 2026** based on the reviewed interim financial statements is **IDR 4,800 billion**. The ratio is **21.25%**, which is above the **20%** threshold. Finance therefore treats this as a material transaction under POJK 17/POJK.04/2020. An independent appraiser is required, and the draft report from **KJPP Lucerne dan Rekan** indicates a market value range of **IDR 1,004–1,048 billion** for the **60%** stake and a fairness opinion conclusion of **fair**.`,
  `The transaction is below **50%** of equity. Based on Finance's reading with Legal, a GMS approval is not required, assuming the fairness opinion remains fair and no conflict-of-interest transaction approval requirement is triggered for FLOG shareholders. Corporate Secretary should align the disclosure timetable with Legal and the exchange calendar.`,
  `Finance requests that the board paper avoid any wording that could imply the headline platform valuation is the amount FLOG will pay for its stake. Direksi should see the bridge from enterprise value to equity value and then to the actual stake price in one table. This will reduce the risk of misunderstanding during Dewan Komisaris review, lender approval, and public disclosure. The same bridge should be used consistently in the UKD, draft disclosure, and any internal Q&A for directors.`,
  `From an accounting and reporting perspective, Finance will assess consolidation treatment and purchase price allocation after signing, with external auditor consultation before completion. The finance integration workstream must also prepare opening balance procedures, intercompany funding controls, treasury signatories, chart-of-accounts mapping, and a reporting calendar that allows FLOG to consolidate the target without delaying listed-company reporting deadlines. These items are not conditions to approve the transaction, but they are completion-readiness matters for the integration plan.`,
  `## Sensitivity`,
  {
    table: [
      [`Case`, `Assumption`, `Implied view`],
      [`Downside`, `Synergy delayed and capex pulled forward`, `Covenant headroom remains but integration payback extends`],
      [`Base`, `Year 3 synergy target delivered and funding mix as above`, `Leverage peaks at 2.3x then trends down`],
      [`Upside`, `Higher routing yield and procurement savings`, `Earlier deleveraging and improved return on invested capital`],
    ],
  },
  `Finance recommends proceeding subject to completion of the CPs identified by Legal, final bank documentation with PT Bank Woodgrove Indonesia, no material adverse change before completion, and Corporate Secretary ensuring the board paper clearly distinguishes enterprise value, 100% equity value and the actual price for the **60%** stake.`,
  `The Direksi resolution should authorise management to finalise immaterial drafting changes, but not to increase the purchase price, waive escrow, waive a Legal CP, or change the funding mix materially without returning to Direksi. Finance also recommends a monthly post-completion dashboard covering leverage, cash generation, integration spend, synergy capture, capex commitments and tax-escrow status until the acquisition is fully embedded in the FLOG reporting cycle.`,
];

export const INPUT_LEGAL_TAX = [
  `# Proyek Kutub – Ringkasan Hasil Due Diligence Hukum dan Perpajakan serta Persetujuan yang Diperlukan`,
  {
    table: [
      [`Tanggal`, `1 Oktober 2026`],
      [`Dari`, `Yulia Siregar, VP Legal; Ferry Gunawan, Head of Tax`],
      [`Kepada`, `Direktur Utama, Direktur Keuangan, Corporate Secretary`],
      [`Klasifikasi`, `Rahasia – Informasi Orang Dalam`],
    ],
  },
  `## Ruang lingkup dan adviser`,
  `Legal dan Pajak telah melakukan due diligence terbatas atas PT Coho Rantai Dingin untuk mendukung Proyek Kutub. Ruang lingkup mencakup pendirian dan kewenangan korporasi, kepemilikan saham, kontrak pelanggan material, kontrak sewa lokasi utama, perizinan rantai dingin dan farmasi, ketenagakerjaan pada level dokumen, kepatuhan lingkungan, perpajakan, litigasi, dan persetujuan yang diperlukan untuk penandatanganan serta penyelesaian transaksi. Pekerjaan ini dibantu oleh Kantor Hukum Adatum & Rekan (adatum.example) untuk aspek hukum Indonesia dan Konsultan Pajak Contoso Advisory (contoso.example) untuk review pajak historis.`,
  `Pemeriksaan dilakukan berdasarkan dokumen virtual data room, sesi Q&A dengan manajemen target, dan konfirmasi terbatas dari penjual. Belum semua dokumen asli diperiksa. Karena itu, temuan di bawah harus diperlakukan sebagai dasar penyusunan CP, covenant, indemnity, dan disclosure schedule dalam perjanjian jual beli saham. Kami tidak merekomendasikan penandatanganan sebelum CP yang bersifat fundamental dimasukkan secara tegas dalam dokumen transaksi.`,
  `Untuk menghindari salah tafsir dalam board paper, Legal membedakan antara persyaratan pendahuluan, covenant pasca-penandatanganan, indemnity, dan monitoring item. Tidak semua temuan harus menjadi CP. CP hanya digunakan untuk hal yang apabila tidak terpenuhi akan mengubah kemampuan FLOG menyelesaikan transaksi atau menjalankan aset utama secara aman. Temuan lain tetap penting, tetapi cukup ditangani melalui covenant, escrow, disclosure, atau integration action plan.`,
  `## Temuan utama due diligence`,
  {
    table: [
      [`Temuan`, `Risiko`, `Mitigasi`],
      [`Sertifikat CDOB rantai dingin dari BPOM berakhir 31 Oktober 2026`, `Tanpa perpanjangan yang berlaku pada completion, layanan farmasi dapat terganggu dan pelanggan regulated dapat menahan volume`, `Jadikan CP: sertifikat diperpanjang dan berlaku pada tanggal penyelesaian`],
      [`Sewa cold storage Cikarang dengan PT Litware Properti memuat change-of-control clause`, `Pelanggaran klausul dapat memicu default atau renegosiasi sewa lokasi kunci`, `Jadikan CP: persetujuan tertulis landlord diperoleh sebelum completion`],
      [`Kontrak pelanggan farmasi utama memiliki hak terminasi karena change of control`, `Pelanggan dapat mengurangi volume atau meminta pricing concession`, `Minta comfort letter dan rencana komunikasi; tidak kami usulkan sebagai CP`],
      [`Top 5 customers mewakili 54% revenue`, `Konsentrasi pelanggan meningkatkan risiko kehilangan pendapatan jika integrasi mengganggu layanan`, `Masukkan covenant layanan dan account-retention plan dalam rencana integrasi`],
      [`Pemeriksaan pajak FY2023 PPN/PPh dengan potensi eksposur Rp38 miliar`, `Surat ketetapan atau sengketa dapat mengurangi nilai ekonomi transaksi`, `Ditutup dengan escrow Rp51 miliar dan indemnity pajak pre-closing`],
      [`Target mencatat keuntungan one-off Rp24 miliar dari penjualan tanah di Medan pada 2025`, `Perlakuan pajak atas keuntungan perlu didukung dokumen nilai perolehan dan bukti pelaporan`, `Masukkan dalam disclosure schedule dan carve-out pajak yang dilindungi escrow`],
      [`Sertifikasi halal handling masih berlaku`, `Risiko rendah untuk pelanggan makanan tertentu`, `Monitoring masa berlaku dan kewajiban label/handling dalam integrasi`],
      [`AMDAL/UKL-UPL tidak menunjukkan denda material`, `Risiko lingkungan terkendali pada dokumen yang diperiksa`, `Covenant kepatuhan lingkungan tetap dimasukkan`],
      [`Unit refrigerant HCFC-22 masih digunakan pada sebagian fasilitas`, `Program phase-out membutuhkan replacement unit sebelum 2030`, `Masukkan dalam rencana capex dan covenant kepatuhan lingkungan`],
    ],
  },
  `## Perpajakan`,
  `Fokus pajak utama adalah pemeriksaan FY2023 terkait PPN/PPh dengan estimasi potensi eksposur **Rp38 miliar**. Angka ini belum merupakan ketetapan final, tetapi cukup material untuk memerlukan perlindungan kontraktual. Head of Tax merekomendasikan escrow **Rp51 miliar** dan indemnity khusus untuk seluruh kewajiban pajak periode sebelum locked-box date, termasuk bunga, sanksi administrasi, dan biaya sengketa. Penjual harus berkewajiban memberikan dokumen pendukung dan ikut menandatangani korespondensi yang secara wajar dibutuhkan untuk pembelaan pajak.`,
  `Terkait keuntungan one-off **Rp24 miliar** dari penjualan tanah di Medan pada 2025, target menyatakan sudah melakukan pengakuan dan pelaporan pajak. Namun kami belum menerima seluruh dokumen pendukung perolehan historis, bukti pembayaran pajak, dan rekonsiliasi ke laporan keuangan. Hal ini tidak kami usulkan sebagai CP terpisah sepanjang escrow dan indemnity pajak mencakupnya secara jelas.`,
  `SPA perlu memuat hak FLOG untuk mengendalikan atau setidaknya menyetujui strategi penyelesaian sengketa pajak yang dapat berdampak pada escrow. Penjual tidak boleh menyelesaikan pemeriksaan pajak dengan cara yang menimbulkan kewajiban tambahan bagi target setelah completion tanpa persetujuan FLOG. Kami juga merekomendasikan kewajiban penjual untuk menyimpan dan memberikan dokumen pajak historis, termasuk faktur pajak, bukti potong, korespondensi fiskus, dan working paper yang relevan.`,
  `## Benturan Kepentingan`,
  `Kami mencatat bahwa **Ibu Laras Pratiwi, Komisaris Independen FLOG**, duduk pada investment committee **Blue Yonder Capital Fund II**, yaitu penjual dalam Proyek Kutub. Posisi tersebut menimbulkan benturan kepentingan yang harus dideklarasikan secara tertulis sebelum pembahasan di Dewan Komisaris. Beliau tidak boleh ikut mengambil bagian dalam proses pemberian persetujuan Dewan Komisaris, termasuk rapat, sirkulasi keputusan, diskusi informal, atau pemberian rekomendasi kepada komisaris lain. Corporate Secretary perlu menyiapkan catatan recusal dan memastikan prosedur POJK 42/POJK.04/2020 diikuti secara konservatif.`,
  `Benturan ini tidak otomatis menjadikan transaksi tidak dapat dilaksanakan, namun prosesnya harus bersih. Setiap dokumen kepada Direksi dan Dewan Komisaris perlu menyebutkan keberadaan benturan, mitigasi recusal, dan bahwa keputusan komisaris yang tidak berbenturan diambil berdasarkan informasi lengkap, fairness opinion, serta rekomendasi manajemen.`,
  `Corporate Secretary sebaiknya mengatur alur dokumen sehingga Ibu Laras tidak menerima paket evaluasi Dewan Komisaris yang digunakan untuk persetujuan, kecuali informasi yang secara hukum diperlukan untuk deklarasi benturan. Minutes rapat atau keputusan sirkuler harus mencatat bahwa beliau tidak hadir, tidak dihitung dalam pembahasan, dan tidak memberikan suara. Prosedur ini penting karena penjual adalah pihak yang secara ekonomi berkepentingan langsung atas keberhasilan transaksi.`,
  `## Persetujuan dan kepatuhan`,
  `Persetujuan Dewan Komisaris FLOG diperlukan sesuai Anggaran Dasar untuk penyertaan saham material. Selain itu, persetujuan tertulis **PT Fabrikam Nusantara (Persero)** sebagai pemegang saham mayoritas diperlukan untuk investasi di atas **Rp500 miliar**. Berdasarkan analisis Finance dan Legal, transaksi merupakan transaksi material menurut POJK 17/2020 sehingga laporan penilai independen dan fairness opinion wajib tersedia sebelum Direksi mengambil keputusan final dan sebelum keterbukaan informasi disampaikan.`,
  `Keterbukaan informasi harus dilakukan segera, paling lambat sebelum pembukaan perdagangan pada hari bursa berikutnya setelah informasi material terjadi, sesuai ketentuan informasi material sebagaimana telah diubah oleh POJK 45/2024. RUPS tidak diperlukan karena transaksi berada di bawah ambang **50%** ekuitas dan fairness opinion menyatakan wajar, dengan catatan tidak ada perubahan struktur yang menaikkan nilai transaksi. Untuk KPPU, aset gabungan Indonesia melebihi **Rp2,5 triliun**, sehingga notifikasi pasca-penyelesaian wajib dilakukan dalam **30 hari kerja** setelah completion. Notifikasi KPPU bukan condition precedent dan tidak perlu diperoleh sebelum penandatanganan.`,
  `Legal meminta agar UKD tidak menyatakan KPPU sebagai persetujuan sebelum signing. Pernyataan tersebut tidak sesuai dengan analisis kami dan dapat menciptakan CP yang tidak diperlukan secara hukum. Yang perlu dilakukan adalah menyiapkan data notifikasi sejak sebelum completion agar pengajuan pasca-penyelesaian dapat dilakukan tepat waktu. Corporate Secretary, Legal, Finance dan penasehat eksternal harus menyepakati draft disclosure dan draft notifikasi sebelum completion, tetapi penyampaiannya mengikuti trigger hukum masing-masing.`,
  `Selain persetujuan formal, dokumen transaksi perlu memuat covenant ordinary course, larangan perubahan kontrak material tanpa persetujuan pembeli, kewajiban mempertahankan izin, kewajiban menjaga key customer relationship, dan hak FLOG melakukan pre-completion access secara wajar. Untuk pelanggan farmasi yang memiliki hak terminasi karena change of control, kami merekomendasikan comfort letter atau setidaknya meeting note yang menunjukkan pelanggan telah diberi informasi dan tidak menyatakan keberatan material sebelum completion.`,
  `## Daftar condition precedent`,
  `Legal dan Pajak merekomendasikan daftar CP berikut dimasukkan secara lengkap dalam resolusi Direksi dan dokumen transaksi:`,
  `- 1. Persetujuan Dewan Komisaris FLOG sesuai Anggaran Dasar (Komisaris Independen yang memiliki benturan kepentingan tidak ikut memberikan persetujuan).`,
  `- 2. Persetujuan tertulis pemegang saham utama PT Fabrikam Nusantara (Persero) sesuai Anggaran Dasar FLOG untuk penyertaan di atas Rp500 miliar.`,
  `- 3. Persetujuan pemilik lahan (PT Litware Properti) atas perubahan pengendalian untuk sewa gudang berpendingin Cikarang.`,
  `- 4. Sertifikat CDOB (Cara Distribusi Obat yang Baik) rantai dingin dari BPOM milik target diperpanjang dan berlaku pada tanggal penyelesaian (sertifikat saat ini berakhir 31 Oktober 2026).`,
  `- 5. Tidak terjadi perubahan merugikan yang material (no material adverse change) sampai tanggal penyelesaian.`,
  `Dengan memasukkan CP di atas, Legal dan Pajak dapat mendukung kelanjutan Proyek Kutub menuju penandatanganan pada akhir Oktober 2026 dan penyelesaian pada Desember 2026, sepanjang tidak ada temuan baru yang mengubah profil risiko transaksi.`,
  `Untuk naskah keputusan Direksi, mohon seluruh CP ditulis sebagai syarat kewenangan manajemen menyelesaikan transaksi, bukan sekadar daftar tindakan lanjutan. Jika Direksi memberi kuasa kepada Direktur Utama dan Direktur Keuangan, kuasa tersebut harus dibatasi oleh terpenuhinya CP, ketersediaan fairness opinion final, tidak adanya perubahan merugikan yang material, dan pelaksanaan keterbukaan informasi sesuai jadwal pasar modal.`,
];

export const INPUT_OPERATIONS = [
  `# Proyek Kutub – Kajian Operasional dan Rencana Integrasi 100 Hari`,
  {
    table: [
      [`Tanggal`, `30 September 2026`],
      [`Dari`, `Heru Santoso, Direktur Operasi`],
      [`Kepada`, `Direktur Utama, Direktur Keuangan, Corporate Secretary`],
      [`Klasifikasi`, `Rahasia – Proyek Kutub`],
    ],
  },
  `## Ringkasan operasional`,
  `Dari sisi Operasi, Proyek Kutub memberikan akses langsung ke platform cold-chain nasional yang dapat diintegrasikan dengan jaringan FLOG. PT Coho Rantai Dingin memiliki **11 cold storage sites** di Cikarang, Surabaya, Medan, Makassar dan lokasi lain, serta **420 reefers** dengan usia rata-rata **7.8 years**. Footprint ini melengkapi jaringan dry logistics FLOG, terutama untuk pelanggan makanan beku, farmasi, dan e-grocery yang membutuhkan kombinasi ambient dan temperature-controlled distribution.`,
  `Kondisi aset secara umum dapat dioperasikan, tetapi bukan aset baru. Backlog capex yang kami identifikasi sebesar **Rp180 miliar** terutama berkaitan dengan replacement refrigeration units, dock levellers, telemetry, preventive maintenance, dan beberapa perbaikan cold-room insulation. Angka capex ini harus dimasukkan dalam rencana pendanaan terpisah dari harga transaksi agar Direksi melihat total cash requirement setelah completion.`,
  `## Site overlap dan network map`,
  `Overlap paling jelas berada di Cikarang dan Surabaya. Di Cikarang, lokasi target dekat dengan hub FLOG yang melayani pelanggan industrial dan consumer goods. Setelah integrasi, kami melihat peluang shared gate management, cross-dock coordination, consolidated line-haul dispatch, dan combined vendor management untuk security, cleaning, pallet pooling dan utilities monitoring. Di Surabaya, posisi target dapat menjadi cold node untuk Jawa Timur dan koneksi ke Makassar, sementara hub FLOG tetap menangani dry cargo dan customer service.`,
  `Network map yang kami usulkan untuk board paper adalah peta berbasis koridor, bukan daftar alamat. Koridor barat berpusat di Cikarang untuk pharma dan frozen food nasional. Koridor timur memakai Surabaya sebagai staging point untuk Jawa Timur dan Makassar. Medan tetap diperlakukan sebagai regional cold node untuk Sumatra. Seven other sites akan dipetakan sebagai spokes yang menambah reach tetapi tidak langsung menjadi pusat integrasi pada fase awal.`,
  `Kami menyarankan Direksi melihat jaringan ini sebagai hub-and-spoke cold network yang berdampingan dengan jaringan FLOG saat ini. Integrasi fisik gudang tidak selalu berarti satu lokasi harus ditutup atau dipindahkan. Dalam cold-chain, kedekatan dengan pelanggan, stabilitas suhu, dan izin lokasi sering lebih penting daripada konsolidasi ruang. Karena itu, keputusan awal sebaiknya fokus pada dispatch, planning, procurement dan KPI visibility, bukan rationalisation aset secara agresif.`,
  `## Fleet dan basis synergy`,
  `Fleet target terdiri dari **420 reefers** dengan utilisasi yang menurut manajemen masih dapat dinaikkan melalui routing discipline, backhaul matching, dan maintenance planning. Operasi menggunakan **EBITDA 2025 target (laporan manajemen) Rp238 miliar** sebagai basis awal untuk membaca kemampuan bisnis menyerap rencana synergy dan capex. Angka tersebut berasal dari laporan manajemen operasional yang diberikan dalam workshop integrasi; kami belum melakukan rekonsiliasi dengan Finance.`,
  `Area synergy yang paling realistis adalah dispatch consolidation, maintenance procurement, fuel card management, dan vendor standardisation. Kami tidak merekomendasikan perubahan SOP temperature handling sebelum seluruh pelanggan pharma diberi assurance karena service failure di cold-chain jauh lebih mahal dibanding savings jangka pendek.`,
  `Untuk reefers, quick win terbesar adalah discipline pada preventive maintenance dan route planning. Banyak truk berpendingin masih sehat secara teknis, tetapi downtime dapat meningkat jika unit refrigeration tidak dipantau lebih ketat. Kami merekomendasikan fleet health dashboard, spare-parts pooling, dan vendor performance review segera setelah completion. Setiap penghematan bahan bakar harus diuji terhadap risiko temperature excursion; savings tidak boleh mendorong praktik operasional yang merusak compliance.`,
  `## IT/WMS integration`,
  `Target memakai WMS yang terpisah dari FLOG dan memiliki modul temperature logging. Untuk 100 hari pertama, kami merekomendasikan interface ringan: master customer mapping, order-status feed, fleet telematics feed, dan exception reporting. Full migration ke sistem FLOG hanya dilakukan setelah stabilitas data temperature log dan audit trail BPOM dipastikan. Cyber review harus dilakukan bersama Information Security karena WMS menjadi titik kontrol operasional sekaligus bukti kepatuhan layanan.`,
  `Kami tidak merekomendasikan cut-over sistem besar pada fase awal. Pengalaman operasi menunjukkan bahwa gangguan master data pelanggan, SKU, temperature range, atau proof-of-delivery dapat langsung memicu dispute invoice dan eskalasi pelanggan. Pendekatan yang lebih aman adalah data bridge sementara dengan kontrol akses yang jelas, disertai daily reconciliation. Setelah process owner dan data owner disepakati, baru disusun migration roadmap yang lebih permanen.`,
  `## KPI target`,
  {
    table: [
      [`Area`, `KPI target`, `Catatan`],
      [`Cold-room uptime`, `Stabil dan terukur`, `Tidak boleh dikompromikan demi synergy awal`],
      [`On-time delivery`, `Improvement bertahap`, `Fokus rute Cikarang dan Surabaya`],
      [`Temperature excursion`, `Turun melalui monitoring`, `Perlu audit data logger`],
      [`Fleet utilisation`, `Naik melalui routing`, `Butuh dispatch discipline dan telematics`],
      [`Customer retention`, `Tidak ada churn material`, `Koordinasi dengan Strategy dan Commercial`],
    ],
  },
  `## Rencana integrasi 100 hari`,
  {
    table: [
      [`Fase`, `Aktivitas`, `Owner operasi`, `Output`],
      [`Signing sampai completion`, `Confirm site readiness, capex backlog, customer service protocols`, `Integration PMO`, `Day-one checklist`],
      [`Day 1–30`, `Stabilisation, safety briefing, customer communication support, WMS access control`, `Regional Ops`, `Tidak ada gangguan layanan`],
      [`Day 31–60`, `Routing pilot Cikarang–Surabaya, procurement quick wins, maintenance review`, `Fleet Ops`, `Pilot savings dan issue log`],
      [`Day 61–100`, `Scale route optimisation, capex phasing, KPI dashboard, operating model proposal`, `Ops Excellence`, `100-day report to Direksi`],
    ],
  },
  `## Catatan persetujuan dan people`,
  `Menurut pemahaman Operasi, persetujuan KPPU wajib diperoleh sebelum penandatanganan karena aset gabungan grup dan target melewati ambang yang relevan. Mohon Legal memvalidasi posisi ini sebelum board paper diedarkan karena persetujuan tersebut dapat mempengaruhi timetable signing dan completion.`,
  `Target memiliki **1.850 karyawan**. Dari workshop awal, kami perkirakan sekitar **120 posisi** tumpang tindih di Cikarang dan Surabaya, terutama fungsi site administration, dispatch support, dan procurement support. Namun kami memahami Human Capital adalah owner bagian SDM; Operasi hanya menyampaikan observasi lapangan dan tidak mengusulkan keputusan redundansi dalam dokumen ini.`,
  `Untuk governance integrasi, Operasi mengusulkan weekly integration control tower selama 100 hari pertama dengan issue log yang dibagi menjadi safety, service, customer, IT/WMS, fleet, capex dan people dependency. Setiap isu high impact harus memiliki owner dan target penyelesaian sebelum dilaporkan ke Direksi. Kami juga meminta agar procurement synergy tidak dijalankan secara sepihak sebelum Legal memeriksa kontrak vendor target, karena beberapa kontrak cold-chain mempunyai minimum volume atau service-level commitments.`,
  `Kesimpulan Operasi adalah aset dapat diintegrasikan, tetapi nilai transaksi hanya akan tercapai jika FLOG menjaga service continuity. Cold-chain customers membeli keandalan, bukan hanya kapasitas. Karena itu rencana integrasi perlu realistis, bertahap, dan tidak menekan tim lapangan untuk mengejar savings sebelum compliance, safety dan customer assurance terkendali.`,
];

export const INPUT_RISK = [
  `# Proyek Kutub – Kajian Risiko Awal`,
  {
    table: [
      [`Tanggal`, `4 September 2026`],
      [`Versi`, `v1`],
      [`Dari`, `Nadia Putri, VP Risk Management`],
      [`Kepada`, `Direktur Utama, Direktur Keuangan, Corporate Secretary`],
    ],
  },
  `## Catatan dasar kajian`,
  `Kajian awal ini disusun berdasarkan term sheet dan LOI yang tersedia pada tanggal dokumen. Pada saat memo ini dibuat, harga transaksi yang menjadi dasar risk review adalah **Rp940 miliar**, dengan rencana pendanaan **100% kas internal**. Berdasarkan ekuitas FLOG **Rp4.800 miliar**, rasio transaksi adalah **19,58%**, di bawah ambang **20%**, sehingga dalam kajian awal ini kami mencatat transaksi bukan transaksi material dan tidak memerlukan penilai independen. Apabila Finance memperbarui harga, struktur pendanaan, atau interpretasi POJK, risk register perlu diperbarui sebelum dibawa ke Direksi.`,
  `Risk Management memandang Proyek Kutub sebagai transaksi dengan risiko inheren menengah-tinggi karena masuk ke cold-chain regulated logistics, integrasi sistem WMS, konsentrasi pelanggan, dan capex backlog. Namun risiko tersebut dapat dikelola apabila CP Legal, rencana integrasi Operasi, dan governance pasca-akuisisi disiapkan sebelum signing.`,
  `## Risk register`,
  {
    table: [
      [`Risiko`, `Likelihood`, `Impact`, `Rating`, `Mitigasi`],
      [`Integration execution`, `Medium`, `High`, `High`, `Bentuk Integration PMO, 100-day plan, milestone report ke Direksi, dan freeze perubahan SOP kritikal pada fase awal`],
      [`Customer concentration`, `Medium`, `High`, `High`, `Top customers perlu retention plan, sponsor Direksi, service assurance, dan monitoring volume mingguan`],
      [`Regulatory/CDOB`, `Medium`, `High`, `High`, `Pastikan perpanjangan CDOB, gap assessment BPOM, dan audit kesiapan dokumen sebelum completion`],
      [`Key people`, `Medium`, `Medium`, `Medium`, `Retention package untuk site managers dan pharma QA leads; mapping key roles oleh Human Capital`],
      [`Fleet capex`, `High`, `Medium`, `High`, `Validasi usia fleet, preventive maintenance, phasing capex, dan reserve untuk refrigeration unit critical`],
      [`FX on imported refrigeration units`, `Medium`, `Medium`, `Medium`, `Hedging policy untuk imported units, vendor framework, dan contingency dalam capex approval`],
      [`Cyber on WMS`, `Medium`, `High`, `High`, `Security assessment sebelum interface, privileged access review, backup, dan incident response playbook`],
      [`Reputation`, `Low`, `High`, `Medium`, `Communication protocol untuk pelanggan pharma dan food, temperature incident escalation, dan single spokesperson`],
    ],
  },
  `## Risiko integrasi`,
  `Risiko integrasi adalah risiko utama karena bisnis target bergantung pada service reliability. Kegagalan integrasi WMS, route planning, atau SOP cold-room dapat langsung terlihat oleh pelanggan. Risk merekomendasikan pendekatan ring-fence pada fase awal: FLOG mengendalikan governance dan pelaporan, tetapi tidak langsung mengganti sistem operasional target sebelum audit process selesai. KPI yang perlu dimonitor adalah on-time delivery, temperature excursion, complaint rate, WMS downtime, dan fleet availability.`,
  `## Risiko pelanggan dan reputasi`,
  `Konsentrasi pelanggan membuat risiko churn menjadi signifikan. Jika pelanggan farmasi melihat perubahan pengendalian sebagai gangguan, mereka dapat meminta comfort meeting, audit tambahan, atau bahkan menahan volume. Karena itu komunikasi harus didesain bersama Strategy, Commercial, Legal, dan Operasi. Seluruh pesan keluar harus menekankan continuity of service, tidak ada perubahan SOP cold-chain tanpa pemberitahuan, dan dukungan FLOG untuk investasi jaringan.`,
  `Reputasi juga perlu diperhatikan karena FLOG adalah listed company dan bagian dari grup BUMN-style. Kebocoran informasi sebelum keterbukaan dapat memicu spekulasi pasar. Insider list, trading blackout, dan need-to-know access harus diberlakukan sejak awal. Corporate Secretary perlu memastikan nama kode digunakan dalam komunikasi internal yang luas.`,
  `## Risiko regulasi, capex, dan cyber`,
  `Regulatory risk terutama terkait CDOB, halal handling, lingkungan, dan persyaratan pasca-transaksi. CDOB harus ditempatkan sebagai gate item karena tanpa sertifikat yang valid, sebagian revenue pharma berisiko. Capex risk juga tinggi karena fleet reefer dan refrigeration units memiliki kebutuhan maintenance khusus; underinvestment dapat menciptakan downtime atau temperature excursion. Risiko FX muncul karena beberapa refrigeration units dan spare parts harus diimpor.`,
  `Cyber risk pada WMS harus diperlakukan sebagai operational resilience issue, bukan sekadar IT issue. Data temperature log adalah bukti layanan dan kepatuhan. Apabila data hilang atau tidak dapat dipercaya, FLOG dapat menghadapi klaim pelanggan walaupun pengiriman fisik berjalan. Risk merekomendasikan security assessment sebelum koneksi sistem, MFA untuk akses administrator, backup terpisah, dan tabletop incident response setelah closing.`,
  `Risk juga menilai bahwa beberapa mitigasi saling terkait. Misalnya, customer concentration tidak dapat dikurangi hanya oleh Commercial; stabilitas operasi, komunikasi legal atas change of control, dan retention of key site managers sama-sama menentukan. Demikian pula fleet capex mempengaruhi reputasi dan customer churn. Oleh karena itu, risk register harus dipakai sebagai alat steering committee, bukan lampiran statis yang selesai setelah Direksi memberi persetujuan.`,
  `Residual risk akan tetap ada walaupun seluruh mitigasi dijalankan, terutama karena cold-chain adalah bisnis service-critical. Risk meminta agar setiap mitigasi memiliki owner yang jelas, bukti pelaksanaan, dan trigger eskalasi. Tanpa itu, daftar risiko dapat terlihat lengkap di dokumen tetapi tidak mengubah perilaku operasional setelah completion.`,
  `## Rekomendasi Risk Management`,
  `Risk Management mendukung kelanjutan pembahasan dengan syarat risk register diperbarui setelah Finance mengunci harga dan funding, Legal mengunci CP, dan Operasi menyiapkan 100-day plan yang terukur. Sebelum dokumen dibawa ke Direksi, mohon Corporate Secretary memastikan bagian risiko menggunakan data transaksi terbaru, bukan hanya posisi LOI dalam memo awal ini.`,
  `Untuk board paper, kami menyarankan Direksi menerima rekomendasi dengan kontrol tambahan: risk owner lintas fungsi, monthly dashboard, escalation protocol untuk pelanggan utama, dan post-completion review sampai risiko residual turun ke level yang dapat diterima. Jika ada perubahan harga, sumber pendanaan, CP, atau status izin, memo risiko ini harus dianggap perlu update formal sebelum keputusan final.`,
];
