// Authored text for x-report-deck-017. Numbers come from model.mjs so files and answer key cannot drift.
import { CASE as C, DCS, MONTHLY, Q2, TARGETS, COMMITMENTS, DECISION, ERRATUM, OVERTIME_Q3, SAFETY_LOG, company, dcQuarter, monthly } from './model.mjs';

const n = (x) => x.toLocaleString('en-US');
const p1 = (x) => x.toFixed(1);
const v1 = company(false);
const dq = (code) => dcQuarter(code, false);
const dcName = Object.fromEntries(DCS.map((d) => [d.code, d.label]));

// ---------- 01 Request email + QBR deck standard ----------
export const REQUEST = [
  '# QBR 8 October: Distribution Operations section',
  `**From:** ${C.requester.name} (${C.requester.title})`,
  `**To:** ${C.presenter.name} (${C.presenter.title})`,
  `**Cc:** ${C.author.name} (${C.author.title}); ${C.controller.name} (${C.controller.title})`,
  '**Sent:** Monday 5 October 2026, 08:15 WIB',
  '**Subject:** QBR Thursday 8 Oct: Distribution Operations deck, due Wednesday 12:00',
  'Hi Nadia,',
  `As agreed in Friday's prep call, you will present the Distribution Operations section at the Q3 Quarterly Business Review with the Direksi on **${C.qbr}**. Dimas is on leave from Tuesday until 12 October for a family wedding in Padang, so you own the deck. He has sent the Q3 Distribution Operations Performance Report (v1.0, dated 1 October) and the KPI workbook. Please send me the deck by **${C.deckDue}** so Bu Adelia can read it with the pre-reads on Wednesday afternoon.`,
  `Your slot is **${C.slot}**. Bu Adelia has asked for fewer slides and a straight answer on three things the Direksi raised at the Q2 QBR in July:`,
  '- Are we actually serving customers better, or only in the month we report? Wingtip Retail raised late deliveries from Cikarang at their own QBR in September.',
  '- Why is Cikarang running so full, and what do we need to decide before the Q4 peak (11.11, Harbolnas 12.12 and year-end)?',
  '- Did we do what we committed to in July? Please show the three commitments from the Q2 deck and where each one stands.',
  'For reference, these are the three commitments exactly as they appear on slide 4 of the Q2 deck (05):',
  ...COMMITMENTS.map((c) => `- **${c.id}.** ${c.text}. Owner: ${c.owner}.`),
  `The Surabaya overtime baseline in the Q2 deck notes is ${Q2.surabayaOvertimeHours.toLocaleString('en-US')} hours for Q2; Dimas tracks the monthly hours in the workbook.`,
  'Two items need a Direksi decision on Thursday and must be clearly labelled as decisions requested: the overflow warehouse lease near Cikarang and the line-haul carrier tender. Neither has been approved yet, whatever the report wording suggests. Pak Andre has not seen the lease numbers and will want the annual cost on the slide.',
  'Please use the Contoso Niaga QBR template (06) and follow the deck standard below. The Direksi pack goes to the regional office, so the deck is in English. Speaker notes can be in English or Bahasa Indonesia.',
  'Thanks, and shout if anything in the report does not add up. Rudi is the right person for numbers while Dimas is away.',
  'Salam,',
  `${C.requester.name}`,
  `${C.requester.title}`,
  `${C.company}`,
  { pageBreak: true },
  '# Contoso Niaga QBR deck standard (Office of the President Director, rev. 3, March 2026)',
  '> Applies to every division section in the Quarterly Business Review pack. Owner: Chief of Staff.',
  '## 1. Shape',
  `- At most **${C.maxSlides} slides** per division including the title slide. The Direksi reads the pack beforehand; slides support a ${C.slot.split(' plus')[0]} talk.`,
  '- Start with an executive summary slide: three messages in plain sentences, then a scorecard with RAG status.',
  '- One message per slide, written as the slide title (for example "Service improved but is still below target", not "OTIF").',
  '- Use the QBR template. Do not change fonts, colours or the footer.',
  '## 2. Numbers',
  '- Report the **quarter**. A single month may be shown as a trend point, never as the headline.',
  '- Company-level rates (OTIF, fill rate) are calculated from the totals (orders, order lines), **not** the average of the DC percentages.',
  '- Show the change in rates in **percentage points** (pts). Show the change in amounts and costs in **percent**.',
  '- Compare like with like. If a definition or method changed, restate the prior quarter on the new basis or show both, and say so on the slide.',
  '- When a count is below 50 (complaints, incidents), show the count and the change in count, not a percentage change.',
  '- Use the latest corrected figures. If a number changed after the source report was issued, say what changed and why in the speaker notes.',
  '- Currency: IDR. Malaysian costs are converted at the 2026 budget rate already applied in the KPI workbook.',
  '## 3. RAG status',
  '- **Green:** meets target. **Amber:** misses target by no more than 1 pt (rates) or 2% (costs, days, counts with a target above 10). **Red:** misses by more.',
  `- **Warehouse utilisation** is a capacity risk measure: higher is worse. Green ${TARGETS.util.greenMax}% or lower, Amber above ${TARGETS.util.greenMax}% up to ${TARGETS.util.amberMax}%, Red above ${TARGETS.util.amberMax}%.`,
  `- **Customer complaints:** Green ${TARGETS.complaints} or fewer in the quarter, Amber ${TARGETS.complaints + 1} to ${TARGETS.complaints + 3}, Red above.`,
  '- **Safety:** any lost-time injury in the quarter is Red, whatever the frequency rate.',
  '## 4. Accountability',
  '- Show every commitment made at the previous QBR with a status of **Done**, **Partly done** or **Not started**, and the evidence. Do not drop a commitment because it was missed.',
  '- **Done:** the committed deliverable was completed by its due date. **Partly done:** the deliverable itself was started and part of the committed result was achieved. **Not started:** the deliverable itself was not begun by its due date; discussions, drafts and plans do not count as starting it.',
  '- Separate **decisions requested** from things already approved. For each decision show the cost, the alternative and the date it is needed.',
  '- Name accountable owners by role. Do not name other individual employees, and never include disciplinary or individual performance matters; those go through HR.',
  '## 5. Speaker notes and sources',
  '- Every content slide has speaker notes: 3 to 5 sentences of what to say, plus the source of each number (file and section, or workbook sheet).',
  '- Flag anything you could not verify. Do not fill a gap with an estimate unless the slide says it is an estimate.',
];

// ---------- 02 Report ----------
const otifTable = [['DC', 'Orders', 'OTIF orders', 'OTIF Q3', 'OTIF Q2'], ...DCS.map((d) => { const q = dq(d.code); return [d.label, n(q.orders), n(q.otifOrders), `${p1(q.otifPct)}%`, { CKR: '89.8%', SBY: '92.6%', MDN: '93.7%', JHB: '94.0%' }[d.code]]; }),
  ['Company', n(v1.orders), n(DCS.reduce((a, d) => a + dq(d.code).otifOrders, 0)), `${p1(v1.otifPct)}%`, `${p1(Q2.otifPct)}%`]];
const monthTable = [['Month', ...DCS.map((d) => d.name), 'Company'], ...['July', 'August', 'September'].map((m, i) => [m, ...DCS.map((d) => `${p1((MONTHLY[d.code].otif[i] / MONTHLY[d.code].orders[i]) * 100)}%`), `${p1(v1.otifByMonth[i])}%`])];
const costTable = [['DC', 'Cases shipped', 'Cost (IDR m)', 'Cost per case (IDR)', 'vs Q2'], ...DCS.map((d) => { const q = dq(d.code); return [d.label, n(q.cases), n(q.cost), n(q.costPerCase), { CKR: '-0.9%', SBY: '-1.6%', MDN: '+0.8%', JHB: '+1.2%' }[d.code]]; }),
  ['Company', n(v1.cases), n(v1.cost), n(v1.costPerCase), `${p1(((v1.costPerCase - Q2.costPerCase) / Q2.costPerCase) * 100)}%`]];
const utilTable = [['DC', 'Jul', 'Aug', 'Sep', 'Q3 average', 'Pallet positions'], ...DCS.map((d) => [d.label, ...MONTHLY[d.code].util.map((u) => `${p1(u)}%`), `${p1(dq(d.code).util)}%`, { CKR: '38,500', SBY: '14,200', MDN: '7,800', JHB: '6,100' }[d.code]])];
const invTable = [['DC', 'Jul', 'Aug', 'Sep', 'Q3 average'], ...DCS.map((d) => [d.label, ...MONTHLY[d.code].invDays.map(String), p1(dq(d.code).invDays)])];
const appendixMonthly = [['DC', 'Month', 'Orders', 'OTIF orders', 'Cases', 'Cost (IDR m)', 'Complaints'], ...DCS.flatMap((d) => ['Jul', 'Aug', 'Sep'].map((m, i) => [d.name, m, n(MONTHLY[d.code].orders[i]), n(MONTHLY[d.code].otif[i]), n(MONTHLY[d.code].cases[i]), n(MONTHLY[d.code].cost[i]), String(MONTHLY[d.code].complaints[i])]))];

export const REPORT = [
  '# Distribution Operations Performance Report, Q3 2026',
  `**${C.company}** | Distribution Operations Division | Version ${C.reportVersion} | ${C.reportDate}`,
  `Prepared by ${C.author.name}, ${C.author.title}. Data: WMS and TMS extracts of 30 September 2026, Finance cost ledger closed 30 September, HSE log. Distribution: COO office, Finance, Direksi pre-read via the Chief of Staff.`,
  '**Contents:** 1 Executive summary | 2 Scope, data and definitions | 3 Service performance | 4 Volume and cost | 5 Inventory and capacity | 6 Projects and commitments from the Q2 QBR | 7 Health and safety | 8 Customers | 9 Risks and outlook | 10 Recommendations | Appendices A to C',
  '> Classification: Internal. Appendix C is for DC management only.',
  { pageBreak: true },
  '## 1. Executive summary',
  `Q3 was the strongest quarter for Distribution Operations since the network was consolidated in 2024. Service levels climbed every month and **OTIF reached ${p1(v1.otifByMonth[2])}% in September**, ahead of the ${p1(TARGETS.otifPct)}% target, as the Cikarang dock-scheduling changes took effect. Customers are seeing the difference: fill rate improved by ${p1(v1.fillCasePct - Q2.fillLinePct)} points to **${p1(v1.fillCasePct)}%**, the best result we have recorded.`,
  `Cost discipline held through a quarter of rising fuel prices. **Cost per case was IDR ${n(v1.costPerCase)}**, inside the IDR ${n(TARGETS.costPerCase)} target, helped by strong volume of ${n(v1.cases)} cases across the four sites. Inventory days fell to ${p1(company(false).invDays)}, below the 32-day target for the first time this year.`,
  `Our people delivered this safely, with **zero lost-time injuries** in the quarter. Cikarang achieved **excellent utilisation of ${p1(dq('CKR').util)}%**, which shows the network is working hard for the business. Customer complaints remained low at ${v1.complaints} for the quarter.`,
  `To protect service through the Q4 peak, management has approved in principle a temporary overflow warehouse near Cikarang (about IDR ${DECISION.overflow.cost} billion a year), and negotiations with our line-haul carriers are progressing well. Section 10 sets out the recommendations.`,
  '## 2. Scope, data and definitions',
  `The report covers the three Indonesian distribution centres (Cikarang, Surabaya and Medan) and the Johor Bahru hub run by Contoso Niaga Malaysia Sdn Bhd, for July to September 2026. Johor Bahru costs are converted from MYR at the 2026 budget rate used in the KPI workbook.`,
  'OTIF counts an order as on time in full when every line arrives complete within the delivery window agreed with the retail partner. The company figure is calculated from total orders across the network.',
  `From July, fill rate is measured on **cases shipped against cases ordered** instead of order lines, to align with how our largest retail partners measure us on their own scorecards. Case-based fill rate is typically about three points higher than the line-based measure used until Q2. The KPI workbook keeps both measures in the Definitions sheet.`,
  'Cost per case is total warehouse and transport cost (labour, overtime, rent, utilities, equipment, line-haul and last-mile freight) divided by cases shipped from each site. Inventory days are average stock on hand divided by average daily shipments, reported monthly by each DC.',
  'Utilisation is the share of pallet positions occupied at month end. Safety figures come from the HSE log maintained by each DC and consolidated by the HSE coordinator.',
  '## 3. Service performance',
  '### 3.1 OTIF by distribution centre',
  { table: otifTable },
  `All four sites improved on Q2. The network figure for the quarter is ${p1(v1.otifPct)}% on ${n(v1.orders)} orders. Surabaya, Medan and Johor Bahru were each above the ${p1(TARGETS.otifPct)}% target for the quarter. Cikarang, which handles ${Math.round((dq('CKR').orders / v1.orders) * 100)}% of orders, finished the quarter at ${p1(dq('CKR').otifPct)}%.`,
  '### 3.2 Monthly trend',
  { table: monthTable },
  `July was the weakest month. The Independence Day promotions with Wingtip Retail and two other modern-trade partners pulled orders forward into the last week of July, and Cikarang ran out of dock slots on four days. From mid-August the dock-booking rules were tightened: carriers must confirm a slot 24 hours ahead, and late arrivals are moved to the next free slot instead of queueing. September was the first full month under the new rules and Cikarang reached ${p1((MONTHLY.CKR.otif[2] / MONTHLY.CKR.orders[2]) * 100)}% OTIF.`,
  '### 3.3 What drove the misses',
  'We sampled 400 late or incomplete Cikarang orders from July and August. The main causes were dock congestion and late carrier arrival (46%), short picks where stock was in an overflow location not yet registered in the WMS (27%), late order release by the customer service team after credit holds (15%) and damaged cases rejected at the store (12%).',
  'Wingtip Retail raised late deliveries from Cikarang at their September supplier review. Wingtip measures us on the store delivery window, which is narrower than ours for 38 of their 180 stores. We have agreed a joint review of those windows in October.',
  '### 3.4 Fill rate',
  `On the case-based measure the network fill rate was ${p1(v1.fillCasePct)}% in Q3, up from ${p1(Q2.fillLinePct)}% in Q2. The largest improvement came at Cikarang after slow-moving stock was moved out of the forward pick area in August. Short picks caused by stock in unregistered overflow locations remain the biggest cause of lines not filled.`,
  '## 4. Volume and cost',
  { table: costTable },
  `Volume grew ${p1(((v1.cases - 2826000) / 2826000) * 100)}% on Q2, driven by the back-to-school and Independence Day promotions and by Surabaya's strongest month on record in September (${n(MONTHLY.SBY.cases[2])} cases). Total warehouse and transport cost was IDR ${n(v1.cost)} million.`,
  '### 4.1 Cost by type',
  { table: [['Cost type', 'Q3 (IDR m)', 'Q2 (IDR m)', 'Change', 'Comment'],
    ['Direct labour (permanent)', '6,840', '6,710', '+1.9%', 'Annual wage adjustment from July at Medan and Johor Bahru'],
    ['Overtime and agency labour', '2,130', '2,260', '-5.8%', 'Surabaya shift redesign; agency used for the September peak'],
    ['Rent, utilities and external storage', '4,925', '4,520', '+9.0%', 'Includes IDR 380 m external pallet storage for Cikarang'],
    ['Equipment, maintenance and IT', '1,640', '1,598', '+2.6%', 'Includes Medan WMS one-off IDR 96 m'],
    ['Line-haul freight', '6,375', '6,180', '+3.2%', 'Fuel adjustment from 1 September (about IDR 210 m)'],
    ['Last-mile delivery', '3,260', '2,838', '+14.9%', 'Volume growth and more split deliveries to Wingtip stores'],
    ['Total', n(v1.cost), '24,106', `+${p1(((v1.cost - 24106) / 24106) * 100)}%`, '']] },
  'Diesel prices rose in August and our carriers applied the fuel adjustment clause from 1 September, adding about IDR 210 million to line-haul cost in the quarter. Overtime fell at Surabaya after the shift redesign. Cikarang paid IDR 380 million for temporary external pallet storage in August and September while utilisation was high; this is included in its rent line.',
  `Cost per case improved at Cikarang and Surabaya as fixed costs were spread over higher volume. Medan and Johor Bahru are smaller sites with higher unit costs; Medan also carried one-off WMS upgrade costs of IDR 96 million in August.`,
  '### 4.2 Carrier performance',
  { table: [['Carrier (line-haul)', 'Lanes', 'Share of loads', 'On-time pick-up', 'On-time arrival', 'Claims (cases)'],
    ['PT Fabrikam Logistik', 'Cikarang to Surabaya, Semarang', '46%', '93.8%', '91.2%', '1,140'],
    ['PT Tailspin Ekspres', 'Cikarang to Bandung, Jabodetabek cross-dock', '31%', '96.1%', '94.7%', '610'],
    ['PT Alpine Kargo', 'Medan region, Sumatra lanes', '23%', '95.0%', '93.9%', '420']] },
  'Fabrikam handles almost half of our line-haul loads and accounts for most of the late arrivals at Cikarang docks in July. Its on-time arrival improved from 88.4% in July to 93.5% in September after the dock-booking change. All three contracts expire on 31 December 2026; the current rates were set in 2023.',
  '## 5. Inventory and capacity',
  '### 5.1 Inventory days',
  { table: invTable },
  'Inventory days improved at every site except Johor Bahru, which held extra stock of air conditioners for a Malaysian retail promotion in September.',
  '### 5.2 Utilisation',
  { table: utilTable },
  `Cikarang delivered excellent utilisation of ${p1(dq('CKR').util)}% on average across the quarter and ${p1(MONTHLY.CKR.util[2])}% at the end of September. This means we are getting full value from the site we pay for. Surabaya and Johor Bahru are well used; Medan has room for growth.`,
  'For the Q4 peak, Category Management has forecast inbound volume 18% above Q3 for October to December, mainly televisions, small kitchen appliances and air conditioners ordered for 11.11, Harbolnas on 12 December and year-end promotions. On that forecast, Cikarang utilisation would reach about 96% in November. Above 92% the site loses forward pick locations, put-away slows and the short-pick rate rises, which is what we saw on four days in July.',
  '### 5.3 Options for Q4 capacity at Cikarang',
  { table: [['Option', 'Extra pallet positions', 'Cost', 'Ready by', 'Main risk'],
    ['A. Lease overflow warehouse, Cikarang industrial estate (12 months)', '6,000', 'About IDR 4.2 bn a year incl. racking', '1 November if signed by 12 October', 'Fixed cost through Q3 2027 if peak volume does not repeat'],
    ['B. Continue external pallet storage day by day', 'Up to 3,000 (provider capacity)', 'About IDR 190 m a month at Q3 rates; higher in peak', 'Immediate', 'Provider has no guaranteed space in November and December'],
    ['C. Move slow movers to Surabaya and delay inbound with suppliers', 'About 2,500 freed', 'Transfer freight about IDR 300 m; supplier penalties unknown', '3 to 4 weeks', 'Longer lead times for Jabodetabek stores; transfers distort site volumes']] },
  'Distribution Operations recommends option A. Option B cannot cover the forecast peak on its own; option C helps but cannot be done in time for 11.11 and would add inter-DC transfers.',
  '### 5.4 Site notes',
  `**DC Cikarang (${DCS[0].head}).** The site served ${n(dq('CKR').orders)} orders in the quarter. Dock-booking changes in August cut average truck waiting time from 3.4 hours to 1.6 hours. The forward pick area was re-slotted in August; 1,900 slow-moving SKUs were moved to high racking. Short picks from stock in unregistered overflow locations remain the main operational issue.`,
  `**DC Surabaya (${DCS[1].head}).** The three-shift pattern started on 7 July. September volume was the highest on record. The site supported the air conditioner rebalancing for the Malaysian promotion in September. A stock-count discrepancy on 14 August was investigated and closed (see Appendix C).`,
  `**DC Medan (${DCS[2].head}).** The WMS upgrade went live on 24 August. Pick accuracy improved to 99.6% in September. Medan has spare capacity and could take some Sumatra-bound stock now held at Cikarang.`,
  `**Johor Bahru hub (${DCS[3].head}).** OTIF was the best in the network for the third quarter running. Inventory days rose temporarily for the September air conditioner promotion. Costs are converted at the 2026 budget rate.`,
  '## 6. Projects and commitments from the Q2 QBR',
  '### 6.1 WMS upgrade at DC Medan',
  'The WMS upgrade at Medan went live on 24 August 2026, a week ahead of the 31 August commitment, after a two-weekend cutover. Pick accuracy at Medan improved from 99.1% to 99.6% in September. The one-off cost of IDR 96 million was within budget.',
  '### 6.2 Surabaya overtime',
  'The new three-shift pattern at Surabaya started on 7 July. Overtime has trended down every month and the team is confident the reduction will continue in Q4 now the new roster has settled. Agency staff were used for the September volume peak instead of overtime where possible. Monthly overtime hours are in the KPI workbook.',
  '### 6.3 Line-haul carrier contracts',
  'Negotiations with our three incumbent line-haul carriers are progressing well. We have held informal discussions on rates and service levels and received indicative proposals. Procurement has prepared a draft tender pack, and we plan to issue the formal tender in Q4 so that new rates can apply from the 2027 contract year.',
  '### 6.4 Proyek Nusa support',
  'Distribution Operations supported the SAP S/4HANA cutover rehearsals with two super-users per site. Order release ran without disruption during hypercare, and no OTIF impact was recorded in September.',
  '## 7. Health and safety',
  `The network recorded **zero lost-time injuries** in Q3, maintaining our record from Q2. The HSE log shows two first-aid cases (Surabaya in August, Johor Bahru in September), one medical treatment case at Medan in August and two near misses at Cikarang. The near miss with a faulty reach-truck reversing alarm was found on a pre-use check, which shows the inspection routine is working.`,
  'Total hours worked across the four sites were about 2.4 million. The safety walk programme was extended to Johor Bahru in August, and all forklift operators completed refresher training by 30 September.',
  '## 8. Customers',
  `Customer complaints remained low at ${v1.complaints} for the quarter across more than ${n(Math.floor(v1.orders / 1000) * 1000)} orders. Nine were about late deliveries from Cikarang, five about damaged goods, three about documentation errors and one about a wrong delivery address. All complaints were closed within the 10-working-day service level.`,
  'Wingtip Retail scored us 3.6 out of 5 in their September supplier review, unchanged from June. Their main concern was the store delivery window at Cikarang-served stores in Jabodetabek.',
  '## 9. Risks and outlook',
  '- **Q4 peak capacity at Cikarang.** Forecast utilisation of about 96% in November without extra space. Impact: lower OTIF and more short picks during the most important trading weeks.',
  '- **Carrier rates.** The current line-haul contracts expire on 31 December 2026. Carriers have signalled rate increases of 6 to 9% for 2027.',
  '- **Proyek Nusa stabilisation.** Any order-release delay in the new ERP during peak would hit OTIF directly.',
  '- **Rupiah weakness** raises the cost of imported handling equipment and spare parts.',
  'We expect OTIF to reach 95% in Q4 as the dock-booking changes take full effect, provided the capacity issue at Cikarang is addressed.',
  '### 9.1 Q4 initiatives',
  { table: [['Initiative', 'Owner (role)', 'Milestone', 'Expected effect'],
    ['Register all overflow locations in the WMS at Cikarang', 'DC Cikarang Head', '31 October', 'Fewer short picks; fill rate up'],
    ['Joint delivery-window review with Wingtip Retail (38 stores)', 'Head of Distribution Operations', 'Workshop 20 October', 'Fewer late deliveries measured by Wingtip'],
    ['Line-haul carrier tender', 'VP of Procurement', 'Issue October, award by 15 December', 'New rates from 1 January 2027'],
    ['Seasonal agency staff for peak (120 people)', 'DC Cikarang and DC Surabaya Heads', '1 November to 9 January', 'Protect OTIF in peak weeks'],
    ['Forklift traffic-management review after the Medan incident', 'HSE coordinator', '30 November', 'Fewer pedestrian and forklift interactions']] },
  '## 10. Recommendations',
  `1. Proceed with the temporary overflow warehouse near Cikarang (${DECISION.overflow.what.toLowerCase().replace('lease a', 'a')}), at about IDR ${DECISION.overflow.cost} billion a year including racking, already approved in principle by management. The alternative is to keep renting external pallet storage day by day, which cost IDR 380 million in two months of Q3.`,
  '2. Issue the line-haul carrier tender in October so that new contracts are in place before the current ones expire on 31 December 2026.',
  '3. Approve 120 seasonal agency staff for Cikarang and Surabaya from 1 November to 9 January, within the existing Q4 budget.',
  { pageBreak: true },
  '## Appendix A. KPI definitions',
  '- **OTIF:** orders delivered complete within the agreed window divided by orders delivered.',
  '- **Fill rate (from Q3):** cases shipped divided by cases ordered. Until Q2: order lines filled complete divided by order lines ordered.',
  '- **Cost per case:** warehouse plus transport cost divided by cases shipped.',
  '- **Inventory days:** average stock on hand divided by average daily shipments.',
  '- **Utilisation:** occupied pallet positions divided by total pallet positions at month end.',
  '- **LTIFR:** lost-time injuries per one million hours worked.',
  '## Appendix B. Monthly data by DC',
  { table: appendixMonthly },
  '## Appendix C. Surabaya people matters (for DC management)',
  'Following the stock-count discrepancy of 14 August at Surabaya, shift supervisor Agus Setiadi received a written warning on 2 September for not completing the end-of-shift cycle count on three occasions. HR has closed the case.',
  'Picker productivity, September (cases per hour): highest Rina Kusuma 212, Doni Saputra 205, Maya Lestari 198; lowest Fajar Nugroho 121, Siti Rahmawati 118, Andi Wibowo 109. The three lowest pickers have been placed on a coaching plan.',
];

// ---------- 04 Erratum email ----------
const sbyCorr = monthly(true).SBY.cases[ERRATUM.month];
export const ERRATUM_MAIL = [
  '# Correction to Q3 volumes: Surabaya September',
  `**From:** ${C.controller.name} (${C.controller.title})`,
  `**To:** ${C.presenter.name}; ${C.requester.name}`,
  `**Cc:** ${C.author.name}; Lestari Putri (DC Surabaya Head)`,
  `**Sent:** ${C.erratumDate}`,
  '**Subject:** RE: Q3 Distribution Operations report: correction to Surabaya September volume',
  'Hi Nadia, Yusuf,',
  `While reconciling the Q3 freight accruals today I found that the Surabaya September volume in the report and the KPI workbook includes **${n(ERRATUM.transferCases)} cases** of stock transferred in from Cikarang (stock transport orders STO-4500-2291 to STO-4500-2297, the air conditioner rebalancing before the Malaysian promotion). Those cases were booked as Surabaya outbound shipments when they arrived, but Cikarang had already counted them as its own shipments. They were never shipped to customers by Surabaya.`,
  `Corrected Surabaya September volume: **${n(sbyCorr)} cases** (was ${n(MONTHLY.SBY.cases[2])}). Corrected Q3 network volume: **${n(company(true).cases)} cases** (was ${n(v1.cases)}). Costs are unchanged; the cost ledger was right.`,
  'This pushes the network cost per case above the IDR 8,600 target, and Surabaya will no longer show an improvement on Q2. Please recalculate from the workbook with the corrected volume; I have not updated the workbook because Dimas owns it and is on leave. A report v1.1 will be issued after the QBR.',
  'Nothing else changes as far as I can see. I have not reviewed the safety section; Hendra in Medan is the right person for that.',
  'Regards,',
  `${C.controller.name}`,
  `${C.controller.title}, Finance Business Partnering`,
  `${C.company}`,
];

export const DATA_README = [
  `Q3 2026 Distribution Operations KPI workbook. Owner: ${C.author.name}. Issued with report v1.0 on 1 October 2026; Safety_Log refreshed 2 October 2026 08:10 WIB.`,
  'Sheets: Monthly_DC (one row per DC and month), Targets, Q2_Actuals (as presented at the Q2 QBR), Definitions (fill-rate change), Safety_Log, Overtime, Rates.',
  'Johor Bahru costs are converted from MYR at the 2026 budget rate (Rates sheet). Volumes are cases shipped as booked in the WMS.',
];

export { SAFETY_LOG, OVERTIME_Q3, COMMITMENTS, dcName };
